### ISSUE TITLE
Secured Fields field order

### ISSUE THREAD

**Issue by ismaelvacco** [Adyen/adyen-magento#1003]
**Magento version**: 1.9.2.4
**Plugin version**: 2.13.1
**Description**
There is any way to change credit card field order? I need change the credit card number to first and credit card customer name to second. I think that must be possible with DOM manipulation and javascript but it is a workaround.

**Comment by cyattilakiss** [comment]
Hi @ismaelvacco 

In the latest version unfortunately not. We are planning to implement the secured fields component which will give us the freedom of secured fields and the painless implementation of the credit card component, although we don't have any dates fixed.

I think if you try the DOM manipulation, it can cause some unexpected issues, so I wouldn't recommend putting effort into it.

I'm sorry I couldn't help.

Best,
Attila
Adyen
