### ISSUE TITLE
Web SDK holderName placeholder

### ISSUE THREAD

**Issue by grippado** [Adyen/adyen-magento#1004]
**Magento version**: 1.9.2.4
**Plugin version**: 2.13.1
**Description**
During the implementation of the Web SDK, the placeholder personalization part of the credit card 'holderName' field is not reaching the object in question, in any way I have been able to change, and I need to position it, for the version change to to go into production.
Example of implementation below:
![image](https://user-images.githubusercontent.com/550632/57883600-18eb0f00-77fd-11e9-8d68-06e1857b3c8f.png)

**Comment by Aleffio** [comment]
Hi @grippado ,

to set a placeholder for an holdername, you need to set it inside the translations object, inside AdyenCheckout:
```
var translations = {};
translations[locale] = {"creditCard.holderName.placeholder" : "yourplaceholdername"};
var checkout = new AdyenCheckout({
    locale: locale,
    originKey: "<?php echo $originKey;?>",
    loadingContext: "<?php echo Mage::helper('adyen')->getCheckoutContextUrl();?>",
    translations: translations
    });
var card = checkout.create('card', {
...
```

Please let me know if this works for you,
Kind Regards,
Alessio
Adyen

**Comment by grippado** [comment]
Thx @Aleffio, this solution works fine!

I appreciatte your answer!
best reggards
