### ISSUE TITLE
Missed card logo

### ISSUE THREAD

**Issue by tikolakin** [Adyen/adyen-magento#1012]
**Magento version**: 1.14.0.1
**Plugin version**: 2.14.1
**Description**
When amex card entered - it's not recognized as amex card and so card log is not shown
The logo seems to be available - https://checkoutshopper-test.adyen.com/checkoutshopper/images/logos/amex.svg
but the url to the icon is set as `nocard`

Could you please fix it to support consistent experience for customers as long as it worked prior 2.12.0 version
Grand
![image](https://user-images.githubusercontent.com/5860505/58427864-8161a800-80a9-11e9-96a9-bff95a49f900.png)

**Comment by Aleffio** [comment]
Hi @tikolakin ,

The issue should be solved in the latest plugin version,
if not please make sure that American Express is enabled in your Adyen Credit Card configuration inside Magento.
Feel free to reopen the issue if the problem persists.

Kind Regards,
Alessio
Adyen
