### ISSUE TITLE
ApplePay error: "Invalid payment method data"

### ISSUE THREAD

**Issue by lykhouzov** [Adyen/adyen-magento#1024]
**Magento version**: 1.14.4.1
**Plugin version**: "Invalid payment method data"
**Description**
When place an order with applepay (Sandbox account) it shows and error
"Payment Not Complete"
and in logs `adyen_exception.log` i can see and error
```log
Adyen_Payment_Exception: HTTP Status code 422 received, data {"status":422,"errorCode":"14_007","message":"Invalid payment method data","errorType":"validation"} in app/code/community/Adyen/Payment/Exception.php:43
```

After conversation with support team it was found that current implementation is missing two fields mentioned in [documentation](https://docs.adyen.com/payment-methods/apple-pay/custom-integration-apple-pay-web/):
```json

"paymentMethod": {
  "type": "applepay",
  "additionalData.applepay.token": "VNRWtuNlNEWkRCSm1xWndjMDFFbktkQU..."
 },
```
current implementation has only `applepay.token` field.

**Comment by Aleffio** [comment]
Hi, closing this issue since it was solved in 2.15.0 version

Regards,
Alessio
Adyen
