### ISSUE TITLE
Alert message: HTTP Status code 422 received - Cannot submit order from frontend

### ISSUE THREAD

**Issue by atty31** [Adyen/adyen-magento#1031]
**Magento version**: 1.14.4.1
**Plugin version**: x2.15.1
**Description**
Steps to reproduce:
1. composer update adyen/payment
2. add a product in the cart and go to checkout
3. select the credit card option and use one of the master or visa testing cards from : https://docs.adyen.com/development-resources/test-cards/test-card-numbers/#visa
4. submit your order and on the last step an alert message is shown with this content:
`HTTP Status code 422 received, data {"status":422,"errorCode":"174","message":"Unable to decrypt data","errorType":"validation"} `
5. In the adyen_exception.log this message is registered:
`2019-07-03T10:06:29+02:00 ERR (3): 
Adyen_Payment_Exception: HTTP Status code 422 received, data {"status":422,"errorCode":"174","message":"Unable to decrypt data","errorType":"validation"} in /var/www/html/ffm/httpdocs/app/code/community/Adyen/Payment/Exception.php:43
Stack trace:
#0 /var/www/html/ffm/httpdocs/app/code/community/Adyen/Payment/Model/Api.php(825): Adyen_Payment_Exception::throwException('HTTP Status cod...')
#1 /var/www/html/ffm/httpdocs/app/code/community/Adyen/Payment/Model/Api.php(133): Adyen_Payment_Model_Api->doRequestJson(Array, 'https://checkou...', 'AQEqhmfxKo3LbxV...', NULL)
#2 /var/www/html/ffm/httpdocs/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(285): Adyen_Payment_Model_Api->authorisePayment(Object(Mage_Sales_Model_Order_Payment), 41.6, 'cc')
#3 /var/www/html/ffm/httpdocs/app/code/core/Mage/Sales/Model/Order/Payment.php(1089): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Mage_Sales_Model_Order_Payment), 41.6)
#4 /var/www/html/ffm/httpdocs/app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 41.6)
#5 /var/www/html/ffm/httpdocs/app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#6 /var/www/html/ffm/httpdocs/app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#7 /var/www/html/ffm/httpdocs/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): Mage_Sales_Model_Order->place()
#8 /var/www/html/ffm/httpdocs/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#9 /var/www/html/ffm/httpdocs/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#10 /var/www/html/ffm/httpdocs/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#11 /var/www/html/ffm/httpdocs/app/code/core/Mage/Checkout/Model/Type/Onepage.php(819): Mage_Sales_Model_Service_Quote->submitAll()
#12 /var/www/html/ffm/httpdocs/app/code/core/Mage/Checkout/controllers/OnepageController.php(602): Mage_Checkout_Model_Type_Onepage->saveOrder()
#13 /var/www/html/ffm/httpdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#14 /var/www/html/ffm/httpdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#15 /var/www/html/ffm/httpdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /var/www/html/ffm/httpdocs/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 /var/www/html/ffm/httpdocs/app/Mage.php(694): Mage_Core_Model_App->run(Array)
#18 /var/www/html/ffm/httpdocs/index.php(83): Mage::run('ffm_de_de', 'store')
#19 {main}
`

Other info: in the ajax request from: `{base_url}checkout/onepage/saveOrder/form_key/batk95BcMAqP98vv/`

These are the params:

```
payment[method]: adyen_cc

payment[cc_owner] : undefined

payment[encrypted_number] : undefined

payment[encrypted_expiry_month] : undefined

payment[encrypted_expiry_year] : undefined

payment[encrypted_cvc] : 

allValidcard : true

payment[store_cc] : 1

form_key : batk95BcMAqP98vv

agreement[1] : 1
```

**Comment by Aleffio** [comment]
Hi @atty31 ,
Can you please send us a screenshot with your checkout card fields?
Are you able to inspect your browser and see in the network tab if the correct script is loaded?(securedFields.2.2.0.min.js).
If this is the correct script, can you please add a console.log line inside the onChange callback?
https://github.com/Adyen/adyen-magento/blob/99679879c69748bef25b0422177c071980f5fa86/app/design/frontend/base/default/template/adyen/form/cc.phtml#L123
`console.log(state);`
When all the fields are filled, the callback should return a state with 'isValid' set to true, this should set the correct values to pass to the backend, which does not seem to be your case since you have all undefined fields.

Please let me know if you have any questions.
Kind Regards,
Alessio
Adyen

**Comment by atty31** [comment]
Hi @Aleffio ,

Thnx for the quick reply. i needed to update the rewritten phtml file with the one from /base/default/template/adyen/form/cc.phtml/.  Now it works. 

Thank you :)

**Comment by Aleffio** [comment]
Hi @atty31 ,

no problem!
closing the issue,

Kind Regards,
Alessio
Adyen
