### ISSUE TITLE
Undefined variable: storeId

### ISSUE THREAD

**Issue by pkamilp** [Adyen/adyen-magento#1037]
**Magento version**: 1.9.4.1
**Plugin version**: 2.15.1
**Description**:

I am testing testing payments using 3d secure 1 credit cards, transaction fails with error 
`Undefined variable: storeId  in code/community/Adyen/Payment/Model/Api.php on line 384`

`$storeId` variable is not defined at all in `authorise3DPayment` method

**Comment by Aleffio** [comment]
Fix is merged on 2.16.0 and onwards, closing the issue,
thanks for the contribution,

Regards,
Alessio
Adyen
