### ISSUE TITLE
ThreedDS2Utils is not defined

### ISSUE THREAD

**Issue by royarthur-dev** [Adyen/adyen-magento#1044]
**Magento version**: 1.9.4.1
**Plugin version**: 2.16.0
**Description**: the module seems to be not compatible with multishipping
*steps to reproduce :*

- add a product to cart
- view shopping cart
- click on "checkout with multiple addresses"
- continue to billing information
- on the checkout/multishipping/billing/ page, console displays the fllowing javascript error message : "ReferenceError: ThreedDS2Utils is not defined"

**Comment by Aleffio** [comment]
Hi @royarthur-dev 
I created a pull request referencing this issue,
can you please check if it solves the issue?

Thanks,
Alessio
Adyen
