### ISSUE TITLE
GUEST_ID constant not declared

### ISSUE THREAD

**Issue by charleskj** [Adyen/adyen-magento#1048]
Error
--
`PHP Fatal error:  Undefined class constant 'GUEST_ID' in /..../app/code/community/Adyen/Payment/Model/Api.php on line 128`

https://github.com/Adyen/adyen-magento/blob/develop/app/code/community/Adyen/Payment/Model/Api.php#L128

GUEST_ID constant not declared in above class.

**Comment by cyattilakiss** [comment]
Hi @charleskj ,

Thank you for raising the issue.
We merged the hotfix which solves the problem.

Best,
Attila
Adyen

**Comment by charleskj** [comment]
Thanks @cyattilakiss
