### ISSUE TITLE
Apple pay and 3DS redirect fails when store code is used in url.

### ISSUE THREAD

**Issue by JerryBra** [Adyen/adyen-magento#1050]
**Magento version**: 1.9.4.2
**Plugin version**: 2.16
**Description**

Both 
app/design/frontend/base/default/template/adyen/apple_pay.phtml
app/design/frontend/base/default/template/adyen/threeds2.phtml

uses javascript redirects to among other pages the 'checkout/onepage/success' without getting the URL from Magento resulting in broken redirects if store code is present. It's also problematic if the url for the checkout is different.

for example
```JavaScript
window.location = 'checkout/onepage/success';
```
should be 
```php
window.location = "<?php echo $this->getUrl('checkout/onepage/success',
    array('_secure' => true)); ?>";
```

Edit: This has already been partially mentioned in issue #1040

**Comment by Aleffio** [comment]
Hi @slaaxy,

Thank you for your PR!
we are going to review it and merge it.

Kind Regards,
Alessio
Adyen
