### ISSUE TITLE
HTTP Status code 422 received, data {"status":422,"errorCode":"15_002","message":"Required field language missing for device channel browser","errorType":"validation"}'

### ISSUE THREAD

**Issue by hughconway** [Adyen/adyen-magento#1057]
**Magento version**: 1.9.0.1
**Plugin version**: 2.17.0
**Description**

Since upgrading to the latest version of the module, I have had a number of transaction attempts fail with the error code: 'HTTP Status code 422 received, data {"status":422,"errorCode":"15_002","message":"Required field language missing for device channel browser","errorType":"validation"}'

This is an intermittent error as some card transactions are processing correctly, and some are not going through on the first couple of attempts but then are later. I have not been able to replicate it so am having to use customers' descriptions of how the error presents and the error log, but have so far not been able to diagnose the issue.

Here is a stack trace from the latest one: 

    2019-10-04T11:18:22+00:00 ERR (3): 
    exception 'Adyen_Payment_Exception' with message 'HTTP Status code 422 received, data {"status":422,"errorCode":"15_002","message":"Required field language missing for device channel browser","errorType":"validation"}' in /domains/sconch.com/http/app/code/community/Adyen/Payment/Exception.php:47
    Stack trace:
    #0 /domains/sconch.com/http/app/code/community/Adyen/Payment/Model/Api.php(833): Adyen_Payment_Exception::throwException('HTTP Status cod...')
    #1 /domains/sconch.com/http/app/code/community/Adyen/Payment/Model/Api.php(137): Adyen_Payment_Model_Api->doRequestJson(Array, 'https://1d3d870...', 'AQEkhmfuXNWTK0Q...', NULL)
    #2 /domains/sconch.com/http/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(289): Adyen_Payment_Model_Api->authorisePayment(Object(Mage_Sales_Model_Order_Payment), 70, 'cc')
    #3 /domains/sconch.com/http/app/code/core/Mage/Sales/Model/Order/Payment.php(1086): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Mage_Sales_Model_Order_Payment), 70)
    #4 /domains/sconch.com/http/app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 70)
    #5 /domains/sconch.com/http/app/code/core/Mage/Sales/Model/Order.php(886): Mage_Sales_Model_Order_Payment->place()
    #6 /domains/sconch.com/http/app/code/core/Mage/Sales/Model/Order.php(1104): Mage_Sales_Model_Order->_placePayment()
    #7 [internal function]: Mage_Sales_Model_Order->place()
    #8 /domains/sconch.com/http/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
    #9 /domains/sconch.com/http/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
    #10 /domains/sconch.com/http/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
    #11 /domains/sconch.com/http/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
    #12 /domains/sconch.com/http/app/code/core/Mage/Checkout/Model/Type/Onepage.php(789): Mage_Sales_Model_Service_Quote->submitAll()
    #13 /domains/sconch.com/http/app/code/local/Magestore/Onestepcheckout/controllers/IndexController.php(714): Mage_Checkout_Model_Type_Onepage->saveOrder()
    #14 /domains/sconch.com/http/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Magestore_Onestepcheckout_IndexController->saveOrderAction()
    #15 /domains/sconch.com/http/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
    #16 /domains/sconch.com/http/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
    #17 /domains/sconch.com/http/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
    #18 /domains/sconch.com/http/app/Mage.php(684): Mage_Core_Model_App->run(Array)
    #19 /domains/sconch.com/http/index.php(87): Mage::run('www', 'store')
    #20 {main}

And a truncated version of the API log:

    2019-10-04T11:18:21+00:00 DEBUG (7): Array
    (
        [browserInfo] => Array
            (
                [userAgent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
                [acceptHeader] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
                [language] => 
                [colorDepth] => 
                [screenHeight] => 
                [screenWidth] => 
                [timeZoneOffset] => 
                [javaEnabled] => 
            )

It looks like the module is not populating [language] => and so the transaction is being refused by the Adyen servers.

Is there any way to either force the language field to populate or to remove the submission of the language field to avoid it failing validation?

Bryan from the Adyen Technical Support team has asked me to give you (the Adyen developers on GitHub) the PSP reference of 1635701880726356 for the latest failed transaction.
Thanks,

Hugh

**Comment by Aleffio** [comment]
Hi @hughconway ,

This is browser data that should be populated by this js file:
https://github.com/Adyen/adyen-magento/blob/9429c55c6cc0c54ae0c7662c767d18e429639978/app/design/frontend/base/default/layout/adyen.xml#L94

It will be passed by the form here:
https://github.com/Adyen/adyen-magento/blob/697ab6c0521333e94adda2801cc6ca5aa8d05c7b/app/design/frontend/base/default/template/adyen/form/cc.phtml#L96-L104

You can include some additional checks here and/or force the language field.
Do you see some patterns in shopper's behavior or browser? It is odd that it happens only sometimes.

Thanks,
Kind Regards,
Alessio
Adyen

**Comment by Aleffio** [comment]
Closing the issue for now, feel free to reopen it with more details.

Kind Regards,
Alessio
Adyen
