### ISSUE TITLE
Missing image for bank "Handelsbanken"

### ISSUE THREAD

**Issue by HK-Services** [Adyen/adyen-magento#1058]
**Magento version**: 1.9.3.10
**Plugin version**: 2.17.0
**Description**:
Image link doesn't exist: skin/frontend/base/default/images/adyen/HANDELSBANKEN.png

**Comment by msilvagarcia** [comment]
Hey @HK-Services !

Thanks for bringing this issue to our attention. We will add that in the near future.
Meanwhile, you can add one image yourself if you need an urgent fix for this. Just follow the format of other images in the directory and you'll be fine.

Cheers!
Marcos
Adyen
