### ISSUE TITLE
Inconsistent state in Manual Review (Case Management) makes the order impossible to cancel

### ISSUE THREAD

**Issue by MarcoPierozziTriboo** [Adyen/adyen-magento#1068]
**Magento version**: 1.9.4.1
**Plugin version**: 2.17.0
**Description**
When an order is placed in Manual Review from case management, if the order has ever been in payment_review (state), when the notification is processed the order is placed in an inconsistent status/state combination because the notification changes only the status, which should be pending_payment.
By itself it's not an issue, but becomes one when an order in Case Management is canceled because $order->canCancel() returns always false when an order is in payment_review, so the actual result is that th order **is not canceled** when a CANCEL_OR_REFUND notification is received and the order is in payment_review.

This is what happens in one of our store. In this example we use the state adyen_review/pending_payment (status/state) for manual review.

* The Order is placed awaiting notification (payment_review/payment_review)
* Order goes to case management (adyen_review/payment_review <- issue is here, should be adyen_review/pending_payment)
* CANCEL_OR_REFUND notification -> $order->canCancel() return false so order is NOT canceled

The issue can be fixed in app/code/community/Adyen/Payment/Model/ProcessNotification.php:1413

```php
        // if manual review is true use the manual review status if this is set
        if ($manualReviewComment == true && $this->_fraudManualReview) {
            // check if different status is selected
            $fraudManualReviewStatus = $this->_getFraudManualReviewStatus($order);
            if ($fraudManualReviewStatus != "") {
                $status = $fraudManualReviewStatus;
                //Fix starts here
                if($order->getState() == Mage_Sales_Model_Order::STATE_PAYMENT_REVIEW) {
                    $order->setState(Mage_Sales_Model_Order::STATE_PENDING_PAYMENT);
                }
                //fix ends here
                $comment = "Adyen Payment is in Manual Review check the Adyen platform";
            }
        }
```

**Comment by Aleffio** [comment]
Hi @MarcoPierozziTriboo 

Indeed in this case it doesn't work without your fix.
Could you please open a Pull Request with your fix?
Thanks,

Regards,
Alessio
Adyen

**Comment by MarcoPierozziTriboo** [comment]
Pull request created. We also put the fix under 
Adyen_Payment_Model_ProcessNotification::_prepareInvoice() which has the same issue

Thanks for the quick answer :)

**Comment by rikterbeek** [comment]
@MarcoPierozziTriboo,

Thanks! we have merged it so closing the issue.

Regards,
Rik
Adyen
