### ISSUE TITLE
Exporting/Dumping keys to env.php

### ISSUE THREAD

**Issue by bash247** [Adyen/adyen-magento#1090]
**Magento version**: 2.3.4
**Plugin version**: 6.0.0

**Description**
We have multiple environments (dev, stage and live) configured for our magento instance. I noticed that the Adyen module currently dumps the API keys in `config.php`. When these keys are moved to `env.php` and removed from `config.php`, the Adyen module believes there are no keys, and it won't let us use the payment gateway. Currently to work around this, we're having to remove the keys from config and add them via the admin area within Magento.

This could be helpful - https://devdocs.magento.com/guides/v2.3/extension-dev-guide/configuration/sensitive-and-environment-settings.html

**Comment by Aleffio** [comment]
Hi @bash247 ,

Thank you for reporting the issue, 
since this is the repository for the Magento 1 plugin,
could you please copy this issue to our Magento 2 plugin repository?
You can find it here: https://github.com/adyen/adyen-magento2

Thanks!
Alessio
Adyen

**Comment by bash247** [comment]
Thank you. Closing this issue and added here https://github.com/Adyen/adyen-magento2/issues/703.
