### ISSUE TITLE
No error message shown after failed payment

### ISSUE THREAD

**Issue by oblomovx** [Adyen/adyen-magento#335]
When a customer tries to pay but something goes wrong (i.e. the customer cancelled or it's credit card is refused), the customer is redirected to the checkout page again. But the error message associated with the error is not shown on that page.
If the customer moves to another page, the error message is shown there, which can be very confusing.

The error should be shown after the customer is redirected back to the checkout page.

**Comment by rikterbeek** [comment]
Hi oblomovx ,

Thanks for letting us know. The error message is showing on the cart page. We just make it possible to now return to the checkout page. We have to look into if it is possible to show the error here. The checkout modules are very different so don't know if we can use a generic solution in Magento. We have to look into this.

Regards,
Rik
Adyen

**Comment by oblomovx** [comment]
Hi Rik,

Would be great if the customer can be sent back to the checkout and see the error message there. We have another payment method that does redirect to the checkout and shows the message, I can send you the code if you want.

**Comment by rikterbeek** [comment]
Hi oblomovx,

Thanks oblomovx! If you can send me the code that would be great. Then I can look into it and implement it in our module as well.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @oblomovx,

Is this something you can share ?

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @oblomovx,

Is this something you can share ?

Regards,
Rik
Adyen
