### ISSUE TITLE
Suggestion to change modman install name

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/adyen-magento#347]
Extension name is now magento if installing via modman

This is dangerous because too common, and doesnt describe the contents

See the example below

Suggestion:
This should be something like Adyen_magento

![image](https://cloud.githubusercontent.com/assets/11224809/8498764/036d0d9e-218b-11e5-85f2-ef3b4868d842.png)

**Comment by rikterbeek** [comment]
Hi Sean,

I understand the issue. We will look into this. 

Regards,
Rik
Adyen
