### ISSUE TITLE
Releasing Pending Payment Orders

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#387]
Magento holds pending payment orders. This means the stock is reserved. As a result when a customer does not complete their order that the qty is not returned to stock. 

We have seen this happens a lot with credit card payments - esp when the RedirectShopper for 3D validation is used. We now have 20+ orders all with status "Pending Payment"; and I think this is the same case for orders that are paid by using email payment + direct debit

Should there not be an option in the adyen backend where we can set the number of days after which we consider the payment not complete and the stock/quote is released? I can assume that adyen itself also releases payments after a while when it has reason to believe that it "will not happen anymore"

This would really help us out a lot!!!

The solution is also quite simple. And could easily be added using something like this:

```
$olderThan = 8;
$date = date('Y-m-d', mktime(0,0,0, date('m'), date('d') - $olderThan, date('Y')));
$orders = Mage::getModel('sales/order')->getCollection()
    ->addFieldToFilter('state', 'pending_payment')
    ->addFieldToFilter('updated_at', array('lt'=>$date));
foreach ($orders as $order){
    $order->cancel();
    $order->save();
}


```

**Comment by rikterbeek** [comment]
Hi Sean,

This is definitely we can add as an extra option. Only this can be very differently foreach kind of payment method. We will add this in the future.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
Thanks Rik. That would really really help.

Maybe only for Adyen payments
And you can split out the payments that following the pending flow and in
its first draft create a adyen main config setting (and not yet per
payment).
It is true that one would for direct debit wait 5-7 days to expire
and for CC you would expire after 2 hours
But this is important: only for the status pending payment

**Comment by seansan** [comment]
I though it was usefull to elaborate on this issue. Because the situation is a little more complex. I have attached a process flow and screenshot. 

In writing:
- there are 3 important statuses; that are distinctyl different
- Awaiting payment => order is pending => someone went to checkout (don't know anything after that, the Adyen status is then N/A)
- Customer cancels payment method, Magento order is confirmed released. QTY back in stock.
- Payment Pending => order has status payment pending => Customer went to checkout, choose payment and completed all details. Ideal will validate immediately and move to status "New orders", like some others. *But* Paypal, SEPA directdebit, banktransfer can take XXX working days. 

The status "Awaiting payment" should be released and cancelled after a short time; e.g. 10-30 minutes

The status "Payment pending" should be released and cancelled after xxx working days. Depending on the processing time. You might even want to be able to set it per payment type (or Adyen sets it for us per payment type based on the number of realistic days before authorization should occur) - then releases the stock QTY again and cancels order

I hope someone else with more knowledge on the status/order process can add their views on this

Assumptions: orders with status Pending and Payment Pending both hold stock and are not automatically released.  

![example image](https://cloud.githubusercontent.com/assets/652395/9516367/7f2eb282-4ca8-11e5-8aa3-1477d418e55a.JPG)

![process overview 2](https://cloud.githubusercontent.com/assets/652395/9516383/9827a3d4-4ca8-11e5-9b45-d4e7756265ce.JPG)

**Comment by nicolasmetzke** [comment]
You can check out this extension: http://www.magentocommerce.com/magento-connect/magento-pending-orders-automatic-cancelation-with-stockreleaser-by-soon.html

Generally works well. You can configure the delay to cancel the order and release the stock per payment method and set it in minutes, hours or days.

But there are some draw-backs with this (or any extension). It would definitely make sense to have the PSP handle the release of stock, instead of a separate extension. But as temporary solution or for other payment methods it's a good way for not keeping Pending orders pending forever (we use it for banktransfer payments)

**Comment by seansan** [comment]
>> It would definitely make sense to have the PSP handle the release of
stock

I am not sure the PSP would be responsible for the stock. But I can imagine
that Adyen also expires payments after some time (because the money is not
coming and hence we write off the expectation).

This way the order can be set to cancelled or other status via a setting in
the backend ....

**Comment by nicolasmetzke** [comment]
You're right, my statement wasn't correct, but at the end it's the same thing. PSP should manage the state of the order and cancel the order after a certain time if payment is overdue and not coming in. This is exactly what this extension does. After the order gets cancelled, then the items are returned to stock.
