### ISSUE TITLE
Adyen PayPal pending status via hpp

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/adyen-magento#471]
Adyen PayPal pending status via hpp

Is it possible to let PayPal (actually all payments using pending status) to respect the setting: Order status: pending Bank Transfer/SEPA orders

This is what we expect. Also we use it for rule creation and follow up

When PayPal does not authorize immediately but instead issues a bank transfer then PayPal uses a different status flow and pending status as defined in settings is ignored

**Comment by rikterbeek** [comment]
Hi shirtsofholl,

I don't really understand your question. Paypal orders and Bank transfers are two different payment methods. Paypal authorization is very quick so you will get the AUTHORISATION notification normally in a couple of minutes.

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
Yes in 80% of the cases

But not when the customer does not have enough funds (20%)

(in the background a debit is created from an account to paypal - and just
like adyen SEPA debit this takes some days)

In this case the payment is completed after some days but remains in status
pending all this time

So this is why I think it should also have tthe status "payment pending"
(which is the case)








_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2015-11-30 9:39 GMT+01:00 Rik ter Beek <notifications@github.com>:

**Comment by rikterbeek** [comment]
Hi shirtsofholl,

Could you send in a ticket to magento@adyen.com with some pspreference numbers of payments with this issue? Then we can have a closer look in what has happened.

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
Was sent ...

most important is that paypal also has 2 flows
- 1 direct payment
- other for (delayed) payments like CC or where a SEPA debit is issues to
add funds

the second flow should also follow the Ayden "Pending payment status"
(under Order status: pending Bank Transfer/SEPA orders)

thanks






Wij maken het graag voor je in orde.

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2015-11-30 10:00 GMT+01:00 Rik ter Beek <notifications@github.com>:

**Comment by rikterbeek** [comment]
Hi shirtsofholl,

I understand your issue. If you have configured your PayPal account against a bank account and don't have funds on his account it can take up a few days till the money is withdrawn. You can see it in the resultUrl that is then pending instead of authorized. The only thing we can do is add generic pending notification for you then you will get updates for all payment methods when they are pending. Then on the pending notification we can build in a check if PayPal account use pending status. 

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
Exactly. Sounds great.

I also made an overview of this situation before - in another call where we
drew two flows: instant authorization and flows that use a pending status.
All flowws that have a possible pending status flow should follow this flow
and respect the custom pending status in Adyen.



Wij maken het graag voor je in orde.

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2015-12-01 10:41 GMT+01:00 Rik ter Beek <notifications@github.com>:

**Comment by eperrotta** [comment]
Hi,
is there any news on this topic?
We have a situation where would be *really* great if we could get the paypal pending_reason when a paypal payment returns with Pending status.
Would this be possible?

Thanks a lot

**Comment by rikterbeek** [comment]
Hi @eperrotta,

That is not possible. You will get back a resultUrl pending and when the payment is authorised you will get a AUTHORISATION notificatotion. For non-instant payments it has the same flow as banktransfers.

Regards,
Rik
Adyen
