### ISSUE TITLE
Excluding PSP referal spam from GUA

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#475]
Hi, we are trying to exclude PSP referal spam from GUA ... and because this runs through the Ayden platform and extension we are logging this issue.

We are seeing more and more traffic from Ideal, Securecheck and other external payment providers accessed via the Magento module, then Adyen platform, then redirected to payment gateways and back again to the website. 

Maybe the adyen forwarding can help solve this issue. Please read the articles below for more detail on the issue.

https://www.optimizesmart.com/tracking-true-referrals-in-google-analytics-when-using-paypal-and-other-payment-gateways/

http://blog.analytics-toolkit.com/2015/payment-gateway-referrer-exclusions-google-analytics/

![image](https://cloud.githubusercontent.com/assets/652395/11637576/7be0cf96-9d22-11e5-8afe-2ad2ebe8e06a.png)
om

**Comment by seansan** [comment]
Maybe we can create an option to add ?utm_nooverride=1 to the referal to the success page that is set in Adyen settings?

/checkout/payment/success?utm_nooverride=1

This was the only method before Universal Analytics. However, prior to UA there was also much less need for it, since for a very long time Google Analytics wouldn’t start a new session for the same visitor if an old one has not yet expired. Then, when they made the change the need to use utm_novverride=1 suddenly jumped and that’s why they added the Referral Exclusion List as a feature.

utm_nooverride=1 is a parameter that you attach to your payment gateway return pages. Say your return page is /checkout/payment/success. You need to provide this URL to your payment gateway: /checkout/payment/success?utm_nooverride=1 . This way Google will ignore the referrer information for this session if there is already another session in progress. This is not what this parameter was originally intented for, but it does the job nicely as I can confirm through my deployment of such solutions.

Remember, you need to do this for all links from the payment gateway to your site and this is not a recommended solution if you are on Universal Analytics.

**Comment by rikterbeek** [comment]
Hi Sean,

I have no idea about this at all. Internally we don't have any knowledge about external analytics software. We can not implement this because we don't have the knowledge to support it. I advise you to make changes in your situation where needed. Do this in a clean way so you can still update the module example of this is using event handlers. If you are missing some event handlers let us know we can always add this.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
GUA is quite common to almost 99% ;P
And because you maybe do not know about this issue: this is why we reported
it & added two references

If possible we need to be able to influence the return url (the url that is
called when the payment confirmation goes back to the shop and shows the
success page). Here we need to add a variable to the url string that is
being called ...

**Comment by seansan** [comment]
An option would be to add replace

`$this->_redirect('checkout/onepage/success');`

with

`$myargs = array('utm_nooverride' => '1'); // can be set depending on config
$this->_redirect('checkout/onepage/success', $myargs);`

**Comment by seansan** [comment]
Or can we se this in Adyen settings as the ReturnUrl? 

```Skins >> skincode >> ReturnURL```

http://store.com/adyen/process/success
to
http://store.com/adyen/process/success?utm_nooverride=1

and would this also work in a multistore environment? we see _redirect to /success a lot in the code

**Comment by rikterbeek** [comment]
Hi Sean,

If you are using the same skin with different stores with different urls you need to create a skin for every store. 

Regards,
Rik
Adyen

**Comment by seansan** [comment]
Interesting. This works currently and was configured by Adyen. 1 skin. 1 result URL. 






Sent from my iPhone.

On 08 Dec 2015, at 15:28, Rik ter Beek <notifications@github.com> wrote:

Hi Sean,

If you are using the same skin with different stores with different urls you need to create a skin for every store.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi Sean,

Great that you solved your problem.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
This was not solved ... only mention is: that to date we use 1 skin as configured by Adyen & also 1 returnUrl is configured .... 

so suppose we want to add the parameter to the return url: where do we do it?

And also are we sure the return url from Adyen settings (adyen backend) is respected? Or rather is the success url taken from the controller in the extension programming? hence explaining why this currently works in a multistore environment

**Comment by seansan** [comment]
Would be great to investigate this futher: http://blog.analytics-toolkit.com/2015/payment-gateway-referrer-exclusions-google-analytics/

and adding utm_nooverride

**Comment by seansan** [comment]
1. Would it be an option to create a config option: 
add utm_nooveride yes/no (default:no)

2. then move all the success redirects to 1 function?
process_succesredirect() {}

3. Where we do the following
if adyen_config[utm_nooveride] then 
  $myargs = array('utm_nooverride' => '1'); // can be set depending on config
  $this->_redirect('checkout/onepage/success', $myargs);
else 
 $this->_redirect('checkout/onepage/success');

**Comment by rikterbeek** [comment]
Hi Sean,

I don't have other merchant complaining about this. Adding a setting for one specific merchant is not 
the path we want to make. What we can do is add an event handler so you can create an observer to launch some specific code that is needed for you without changing our code. Let me know where you would like to have such an event handler.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
I think it would be great to be able to influence the success direct (for
instance add a param or change the location)

**Comment by henryvanderborg** [comment]
Ran into the exact same analytics issue when moving to Adyen. utm_nooverride might solve that. I did however read the parameter might not work or is not advised for Google Universal Analytics (perhaps someone can confirm). If so I can only find the manual solution, using the GA referral exclusion list for each referral [https://support.google.com/analytics/answer/2795830?hl=en ](url)  Downside would be that re-actively you would need to add the exclusion for each (new) payment method, unless you would have some list upfront. Perhaps someone can confirm whether utm_nooverride is useful/best practice for GUA.

**Comment by henryvanderborg** [comment]
Not my expertise, did find a suggestion here: 
[](http://stackoverflow.com/questions/31648105/how-to-exclude-payment-method-as-referral-in-google-analytics-through-code )

**Comment by shirtsofholl** [comment]
I read it is possible to add  a param to the return url, but I dont think we can add it in magento config, nor in the adyen backend. Suppose there is a way to edit this param in the extension or in adyen backend and set ?utm_nooverride=1

it could be solved

![image](https://cloud.githubusercontent.com/assets/11224809/18225200/a0e3084a-71ed-11e6-9257-c6a5820596ee.png)

**Comment by Jitheesh** [comment]
We have exact same issue with adyen redirect links. Why Adyen still thinking this is an issue with specific merchants!! Definitely there is an issue, please resolve it.

**Comment by jimains** [comment]
Hello,

We are definitely a plus one for this issue and it is a problem for us. Manually adding exclusions in GA is a bad way to deal with and way to manual / reactive. 

We have added the suggested:
$myargs = array('utm_nooverride' => '1'); // can be set depending on config
$this->_redirect('checkout/onepage/success', $myargs);

Which seems to help somewhat but we still seeing instances like securesite.co.uk.

As the code for this sits within the Adyen module it seems like it should be resolved at Adyen's end. It is not an edge case or something that would only affect a select few. It is standard to use 3d secure and want to track referrals. 

Please can we have a proper fix?

**Comment by rikterbeek** [comment]
Hi All,

This is now added into our code.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
yesssss .... and in no less then 12 months ;)

We suggested adding it as a config option btw .... 
but if you now think it can be hardcoded then this is fine

Also because the Adyen platform does the redirects it could also be set there (new option next to return url = extra params ... )

**Comment by rikterbeek** [comment]
Hi @seansan,

Something to look into but we want to limit the configurations.

Regards,
Rik
Adyen

**Comment by jimains** [comment]
Hello,

We have deployed the patched module to our live site and left to gather data however, we are still seeing the odd instance of a referral from 3d secure:

<img width="442" alt="screen shot 2016-11-22 at 16 32 08" src="https://cloud.githubusercontent.com/assets/912665/20532289/5f9f9934-b0d1-11e6-9906-eae3076581cf.png">

Any idea why this would still be happening?

**Comment by seansan** [comment]
just to be clear: but this the only one ==> ie all others are gone?

**Comment by jimains** [comment]
@seansan I am actually seeing other 3d secure referrals still too. Has the patch resolved the issue for you?
