### ISSUE TITLE
De volgende betaling (SEPA, zonder capture verzoek) heeft status "Expired"

### ISSUE THREAD

**Issue by paales** [Adyen/adyen-magento#506]
-- EXPIRED
| 1814507156093620 | 400052728 | 21-dec |

Adyen Trace:

| History | Data |
| --- | --- |
| JournalType | date |
| Received | 2015-12-21 17:33:29 CET |
| Authorised | 2015-12-21 17:33:29 CET |
| Expired | 2016-01-18 17:34:32 CET |

Dit ziet er naar uit dat Authorisations na een maand verlopen. Dit gaat niet goed ivm ons model (orders worden ook wel een aangenomen voor verzending, later dan een maand).

Is het wellicht nodig om de betaling opnieuw te proberen als deze expired is? Of is dit een instelling bij jullie welke jullie langer kunnen zetten?

**Comment by rikterbeek** [comment]
Hoi Paul,

Dat is helaas niet mogelijk je zult in dit geval een nieuwe betaling moeten inschieten en op deze betaling een capture moeten doen.

Groet,
Rik
Adyen

**Comment by paales** [comment]
@rikterbeek De situatie is dat we een bestelling inplannen en dus een bevestiging van Adyen willen hebben dat de betaling kan worden uitgevoerd (anders kunnen er bij de klant nog juiste betalingsgegevens opgevraagd worden), maar de bestelling wordt pas na x-weken ingestuurd.

Wellicht is het ook opgelost als we via het Admin Panel handmatig een Recurring contract kunnen aanmaken, dan wordt het ook gevalideerd aan jullie kant.

**Comment by rikterbeek** [comment]
Hoi @paales,

Sla de betaling op als een recurring payment dan kun je een recurring payment later nog inschieten om het bedrag van de rekening af te halen.

Groet,
Rik
Adyen

**Comment by paales** [comment]
"kun je een recurring payment later nog inschieten", dat stukje willen we dus automatisch doen.

**Comment by rikterbeek** [comment]
Hoi Paul,

In deze situatie wil je eigenlijk dat de persoon eerst een zero-auth doet en pas het bedrag wordt gereserveerd als het product wordt verscheept. Je wilt niet dat een klant elke maand dit bedrag krijgt gereserveerd op zijn creditcard en pas na 3 maanden er echt afgehaald wordt. Daarnaast zul je alleen recurring payments moeten toelaten als dit product besteld wordt. Hoe zien jullie dit voor je ?

Groet,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hoor graag als hier nog vragen over zijn.

Groet,
Rik
Adyen
