### ISSUE TITLE
Maybe add some events to Openinvoice?

### ISSUE THREAD

**Issue by EwaldBorger** [Adyen/adyen-magento#527]
Because of additions to our Magento shop, we need to add extra lines to the Openinvoice order lines. 
At the moment this means overriding Openinvoice.php and completely copying the getOptionalFormFields method and repeating this each time a new version comes out.
What would be handy is the addition of one or more events so an observer could alter the optional form fields (additional_data_sign with the openinvoicedata.* lines) before they are encoded.
That would probably mean something like splitting the method in a data gathering and an encoding method and having the encoding method fire an event before encoding, allowing the alteration of the data.

**Comment by rikterbeek** [comment]
Hi Ewald,

This is something we can do. I will have a look how we can do this.

Regards,
Rik

**Comment by rikterbeek** [comment]
Hi Ewald,

We have added a event that you can observe to add fields to the request see:
https://github.com/Adyen/magento/blob/develop/app/code/community/Adyen/Payment/Model/Adyen/Hpp.php#L307-L309

Regards,
Rik
Adyen
