### ISSUE TITLE
Openinvoice::getOptionalFormFields also used in HPP

### ISSUE THREAD

**Issue by EwaldBorger** [Adyen/adyen-magento#538]
That was quite unexpected, we've made changes to the Openinvoice::getOptionalFormFields and while debugging a problem with visa and paypal we found HPP also calls the Openinvoice method (and a bug in our code might have caused the problem).
(we added the tax-over-discount fix, but apparently it is not fully working, so we removed it - rather have some people complain about their Klarna invoice than have people not being able to do a payment).
What is it used for in other HPP payments?

We could have seen this earlier of course, as it is logged in adyen_http-request.log and I could have done a search of course.
Anyway, it's a bit odd, as Openinvoice extends HPP, that HPP would call a method in Openinvoice.

**Suggestion** is to move this to either Adyen_Payment_Model_Adyen_Hpp or Adyen_Payment_Model_Adyen_Abstract, or not :) (we now know this is how it works and can handle accordingly).

**Comment by rikterbeek** [comment]
Hi Ewald,

That is correct we want HPP to send in all data as well for fraud purposes. We could move it so it is more clear that is used for all HPP payment methods.

Regards,
Rik
Adyen

**Comment by EwaldBorger** [comment]
Ok, clear :)
So if the order lines don't add up, a visa/paypal payment is also denied on basis of fraud?
Because that would explain why we have had some payments that couldn't go through because the customer got a "Invalid Request - Unfortunately we were unable to process this request" directly from Adyen.
I'm taking my fixes for Klarna invoices back to the drawing board anyway.

**Comment by rikterbeek** [comment]
Hi Ewald,

No that should not be an issue we would make sure with a extra line that it will be correct. We only give this if the request is not correct.

Regards,
Rik
Adyen
