### ISSUE TITLE
Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/adyen-magento#574]
Error is still sometimes seen, we are on last version

Une transaction de paiement a échoué.
Raison
Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details

**Comment by rikterbeek** [comment]
Hi Shirtsofholl,

Could be something with your checkout module is going wrong in a certain browser.
What checkout module are you using ? I add some extra logging to determine what browser the client is using. Could you add this in your code and when the error returns it should be visible in the adyen_exception.log file what browser the client was using.

Regards,
Rik
Adyen

**Comment by santoshsynapse** [comment]
Hello Adyen,

I am recieving an error : Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details.

Can you please let me inform the possible reasons.

**Comment by santoshsynapse** [comment]
Hello @rikterbeek ,

Below is log generated into adyen_exception.log. 

2016-04-28T04:09:56+00:00 ERR (3): 
exception 'Adyen_Payment_Exception' with message 'Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details' in /home/milaurai/public_html/app/code/community/Adyen/Payment/Exception.php:42
Stack trace:
#0 /home/milaurai/public_html/app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php(239): Adyen_Payment_Exception::throwException('Missing the enc...')
#1 /home/milaurai/public_html/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(276): Adyen_Payment_Model_Adyen_Data_PaymentRequest->create(Object(Mage_Sales_Model_Order_Payment), 388.5, 'cc', 'MilauraIT', '', 'ONECLICK', 1)
#2 /home/milaurai/public_html/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(191): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Mage_Sales_Model_Order_Payment), 388.5, 'authorise')
#3 /home/milaurai/public_html/app/code/core/Mage/Sales/Model/Order/Payment.php(1089): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Mage_Sales_Model_Order_Payment), 388.5)
#4 /home/milaurai/public_html/app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 388.5)
#5 /home/milaurai/public_html/app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#6 /home/milaurai/public_html/app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#7 [internal function]: Mage_Sales_Model_Order->place()
#8 /home/milaurai/public_html/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#9 /home/milaurai/public_html/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#10 /home/milaurai/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#11 /home/milaurai/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#12 /home/milaurai/public_html/app/code/core/Mage/Checkout/Model/Type/Onepage.php(812): Mage_Sales_Model_Service_Quote->submitAll()
#13 /home/milaurai/public_html/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#14 /home/milaurai/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#15 /home/milaurai/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#16 /home/milaurai/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#17 /home/milaurai/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#18 /home/milaurai/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#19 /home/milaurai/public_html/index.php(83): Mage::run('', 'store')
#20 {main}

**Comment by rikterbeek** [comment]
Hi @santoshsynapse,

If you are on the latest version of our module before this exception is thrown the user agent details are logged this could be interesting to know. Do you have any javascript exceptions in your checkout ?

Regards,
Rik
Adyen

**Comment by sanutryzens** [comment]
we are having the same issue and I am using the latest version.
The log in the user agent showing as 
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

I have checked and there is no javascript errors in checkout process and we are using magento out of the box onepage checkout

**Comment by rikterbeek** [comment]
Hi @sanutryzens,

Are you on the latest version of our module? we have just released 2.6.3 with some fixes.

Regards,
Rik
Adyen

**Comment by sanutryzens** [comment]
Hi Rik,

We are getting daily 2-3 error messages which saying the below trace on the log
2016-07-13T03:56:28+00:00 ERR (3): Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2683.0 Safari/537.36
2016-07-13T03:56:28+00:00 ERR (3): 
exception 'Adyen_Payment_Exception' with message 'Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details' in /var/www/vhosts/josephjoseph.com/httpdocs/app/code/community/Adyen/Payment/Exception.php:42
Stack trace:
#0 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php(243): Adyen_Payment_Exception::throwException('Missing the enc...')
#1 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(276): Adyen_Payment_Model_Adyen_Data_PaymentRequest->create(Object(Mage_Sales_Model_Order_Payment), 43.87, 'cc', 'JosephJosephLtd...', 'ONECLICK', 'ONECLICK', 1)
#2 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(191): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Mage_Sales_Model_Order_Payment), 43.87, 'authorise')
#3 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Sales/Model/Order/Payment.php(1089): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Mage_Sales_Model_Order_Payment), 43.87)
#4 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 43.87)
#5 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Sales/Model/Order.php(898): Mage_Sales_Model_Order_Payment->place()
#6 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Sales/Model/Order.php(1116): Mage_Sales_Model_Order->_placePayment()
#7 [internal function]: Mage_Sales_Model_Order->place()
#8 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#9 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#10 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#11 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#12 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Checkout/Model/Type/Onepage.php(812): Mage_Sales_Model_Service_Quote->submitAll()
#13 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#14 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#15 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#16 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#17 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#18 /var/www/vhosts/josephjoseph.com/httpdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#19 /var/www/vhosts/josephjoseph.com/httpdocs/en-us/index.php(19): Mage::run('jj_en_usd', 'store', Array)
#20 {main}

This is not happening for all orders, only some of the orders are getting affected by this issue. 
While went through the above log trace I can see that this is something connected with oneclick payment. Plesae see the below section from the log
#1 /var/www/vhosts/josephjoseph.com/httpdocs/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(276): Adyen_Payment_Model_Adyen_Data_PaymentRequest->create(Object(Mage_Sales_Model_Order_Payment), 43.87, 'cc', 'JosephJosephLtd...', 'ONECLICK', 'ONECLICK', 1)
I have checked the module code and see that this error is triggering when user try to use oneclick payment for CC and when an if condition "if($payment->getAdditionalInformation("encrypted_data") != "") {" is failing.

This is what I so far found

**Comment by sanutryzens** [comment]
#629 created a new issue with full details

**Comment by fxhub** [comment]
Hi, 

I am experiencing the same issu, with the latest version of the Adyen plugin, with an out of the box Magento install and onestepcheckout. 
This specifically happen on chrome and firefox. 

Regards

**Comment by rikterbeek** [comment]
Let's continue in #629
