### ISSUE TITLE
OneStepCheckout HPP OpenInvoice notification

### ISSUE THREAD

**Issue by mrdevries** [Adyen/adyen-magento#583]
When we're using Klarna via Adyen with the OneStepCheckout, we don't get a notification message if we failed the Klarna check. This happens with both the redirect to the checkout and with redirect to cart. Does anybody have a clue how to debug this? Thanks!

**Comment by rikterbeek** [comment]
Hi Marco,

If you are using redirect to cart you should see your shopping cart with the exceptions. Maybe you did some core changes ?
For checkout to checkout the OneStepCheckout maybe does not support the error message that we are sending best to contact the OneStepCheckout module why this is not the case.
If you use the default magento checkout does it then work with redirect to cart ?

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
@mrdevries,

Did you found the issue ?

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
I am closing this issue if there is still some issues let me know.

Regards,
Rik
Adyen
