### ISSUE TITLE
Missing the encrypted data value

### ISSUE THREAD

**Issue by Maikel-Koek** [Adyen/adyen-magento#598]
Hello Rik,

Since we switched to Adyen at OppoSuits, some customers sometimes receive the 'Missing the encrypted data value'-error, see below.
I disabled CSE for now, but the weird thing is that this doesn't appear for all customers, there are successful CC payments.

What could be the cause of this?

`2016-05-31T14:32:49+00:00` ERR (3):
exception 'Adyen_Payment_Exception' with message 'Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details' in /var/www/vhosts/opposuits.com/opposuits.com/.modman/Adyen_Payment/app/code/community/Adyen/Payment/Exception.php:42
Stack trace:
#0 /var/www/vhosts/opposuits.com/opposuits.com/.modman/Adyen_Payment/app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php(243): Adyen_Payment_Exception::throwException('Missing the enc...')
#1 /var/www/vhosts/opposuits.com/opposuits.com/.modman/Adyen_Payment/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(276): Adyen_Payment_Model_Adyen_Data_PaymentRequest->create(Object(Ho_MentalSuits_Model_Order_Payment), 607.09, 'cc', 'OpposuitsCOM', 'ONECLICK', 'ONECLICK', 0)
#2 /var/www/vhosts/opposuits.com/opposuits.com/.modman/Adyen_Payment/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(191): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Ho_MentalSuits_Model_Order_Payment), 607.09, 'authorise')
#3 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Sales/Model/Order/Payment.php(1026): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Ho_MentalSuits_Model_Order_Payment), 607.09)
#4 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Sales/Model/Order/Payment.php(311): Mage_Sales_Model_Order_Payment->_authorize(true, 607.09)
#5 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Sales/Model/Order.php(877): Mage_Sales_Model_Order_Payment->place()
#6 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Sales/Model/Order.php(1095): Mage_Sales_Model_Order->_placePayment()
#7 [internal function]: Mage_Sales_Model_Order->place()
#8 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#9 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#10 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#11 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#12 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Checkout/Model/Type/Onepage.php(774): Mage_Sales_Model_Service_Quote->submitAll()
#13 [internal function]: Mage_Checkout_Model_Type_Onepage->saveOrder()
#14 /var/www/vhosts/opposuits.com/opposuits.com/.modman/Ecomdev_checkitout/app/code/community/EcomDev/CheckItOut/Model/Type/Onepage.php(458): call_user_func_array(Array, Array)
#15 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Checkout/controllers/OnepageController.php(511): EcomDev_CheckItOut_Model_Type_Onepage->__call('saveOrder', Array)
#16 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Checkout/controllers/OnepageController.php(511): EcomDev_CheckItOut_Model_Type_Onepage->saveOrder()
#17 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Mage_Checkout_OnepageController->saveOrderAction()
#18 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#19 /var/www/vhosts/opposuits.com/opposuits.com/.modman/Ho_OfflineMaintenance/app/code/local/Ho/OfflineMaintenance/Controller/Router/Standard.php(55): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#20 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Ho_OfflineMaintenance_Controller_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#21 /var/www/vhosts/opposuits.com/opposuits.com/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#22 /var/www/vhosts/opposuits.com/opposuits.com/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#23 /var/www/vhosts/opposuits.com/opposuits.com/index.php(182): Mage::run('opposuits_nl_nl...', 'store')
#24 {main}`

**Comment by rikterbeek** [comment]
Hi @Maikel-Koek,

This could be because of a certain browser/device. If you have any javascript errors in your checkout our CSE script could not be executed. In the log file above this exception you should see the browser data of the customer please check with these specs if you could reproduce the problem.

Regards,
Rik
Adyen

**Comment by Maikel-Koek** [comment]
Hi Rik,
Here are some of these loglines:

2016-05-31T14:27:34+00:00 ERR (3): Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:46.0) Gecko/20100101 Firefox/46.0

2016-05-31T14:28:17+00:00 ERR (3): Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:46.0) Gecko/20100101 Firefox/46.0

2016-05-31T14:29:08+00:00 ERR (3): Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:46.0) Gecko/20100101 Firefox/46.0

2016-05-31T14:32:40+00:00 ERR (3): Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36

2016-05-31T14:32:49+00:00 ERR (3): Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36

**Comment by rikterbeek** [comment]
Hi @Maikel-Koek,

What is the url I can help you? Did you checked at this yourself if you have any javascript errors on the checkout in these broswers on the mac ?

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @Maikel-Koek,

Did you solve this issue ? Saw that you are not using the default magento checkout so that could cause an issue.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
We also still have this error sometimes. Looks like it is browser related.

**Comment by seansan** [comment]
Looks like the browser v is now also logged. FYI still occurs sometimes

2017-05-08T20:28:21+00:00 ERR (3): Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
2017-05-08T20:28:21+00:00 ERR (3): 
Adyen_Payment_Exception: Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details in app/code/community/Adyen/Payment/Exception.php:42
Stack trace:
#0 app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php(253): Adyen_Payment_Exception::throwException('Missing the enc...')
#1 app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(359): Adyen_Payment_Model_Adyen_Data_PaymentRequest->create(Object(Mage_Sales_Model_Order_Payment), 114.95, 'cc', 'ShirtsofHolland...', 'ONECLICK', 'RECURRING', 0)
#2 app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(267): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Mage_Sales_Model_Order_Payment), 114.95, 'authorise')
#3 app/code/core/Mage/Sales/Model/Order/Payment.php(1089): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Mage_Sales_Model_Order_Payment), 114.95)
#4 app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 114.95)
#5 app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#6 app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#7 app/code/core/Mage/Core/Model/Resource/Transaction.php(105): Mage_Sales_Model_Order->place()
#8 app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#9 app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#10 app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#11 app/code/core/Mage/Checkout/Model/Type/Onepage.php(815): Mage_Sales_Model_Service_Quote->submitAll()
#12 app/code/core/Mage/Checkout/controllers/OnepageController.php(578): Mage_Checkout_Model_Type_Onepage->saveOrder()
#13 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#14 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#15 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 app/Mage.php(683): Mage_Core_Model_App->run(Array)
#18 index.php(89): Mage::run('ovh_nl', 'store')
#19 {main}

**Comment by rikterbeek** [comment]
This should be resolve if there are still issues with the latest version please open a new issue.

Regards,
Rik
Adyen
