### ISSUE TITLE
Openinvoice (Afterpay) Problem sending gender

### ISSUE THREAD

**Issue by oblomovx** [Adyen/adyen-magento#601]
We are currently integrating Afterpay in our checkout. When we submit the payment, the gender should be sent as 1 or 2, but our internal code for the genders are different (on 2 different magenot installations). We currently convert our internal codes to 1 and 2 in /template/adyen/form/openinvoice.phtml , but ideally it should be set correctly in the Adyen code.

**Comment by rikterbeek** [comment]
Hi @oblomovx,

They should never be different so that is very strange. See the sql code:
https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Customer/sql/customer_setup/mysql4-upgrade-1.4.0.0.0-1.4.0.0.1.php#L47-65

Regards,
Rik
Adyen

**Comment by oblomovx** [comment]
I suspect that things go wrong at this line:

https://github.com/Adyen/magento/blob/e1529f620eb94754ff095025626648413591108a/app/code/community/Adyen/Payment/Model/Adyen/Openinvoice.php#L235

Our internal code gets passed to getGenderText , which is not converted correctly because the genderid's must be 1 and 2 in the getGenderText function

**Comment by leonhelmus** [comment]
`class Random_Checkout_Model_Adyen_Openinvoice extends Adyen_Payment_Model_Adyen_Openinvoice {
    /**
     * @param $genderId
     * @return string
     * In our database the valueIds of male and female are : 404 and 405
     */
    protected function getGenderText($genderId)
    {
        $result = "";
        if($genderId == '404') {
            $result = 'MALE';
        } elseif($genderId == '405') {
            $result = 'FEMALE';
        }
        return $result;
    }
}`

**Comment by leonhelmus** [comment]
```
class Athleteshop_Checkout_Model_Adyen_Openinvoice extends Adyen_Payment_Model_Adyen_Openinvoice {
    /**
     * @param $genderId
     * @return string
     * In our database the valueIds of male and female are : 404 and 405
     */
    protected function getGenderText($genderId)
    {
        $result = "";
        if($genderId == '404') {
            $result = 'MALE';
        } elseif($genderId == '405') {
            $result = 'FEMALE';
        }
        return $result;
    }
}
```

**Comment by leonhelmus** [comment]
```
class Random_Checkout_Model_Adyen_Openinvoice extends Adyen_Payment_Model_Adyen_Openinvoice {
    /**
     * @param $genderId
     * @return string
     * In our database the valueIds of male and female are : 404 and 405
     */
    protected function getGenderText($genderId)
    {
        $result = "";
        if($genderId == '404') {
            $result = 'MALE';
        } elseif($genderId == '405') {
            $result = 'FEMALE';
        }
        return $result;
    }
}
```

my gender ids were 404 and 405

**Comment by leonhelmus** [comment]
just rewrite it.

**Comment by oblomovx** [comment]
I'd rather not edit the module code. I have fixed it in the template file, but it's not ideal.

**Comment by rikterbeek** [comment]
Hi,

Found it strange that this can have different IDs. If I look into the setup scripts of magento this is always the first attributes that are created in the table so it should have always be 1 for male, 2 for female. Do you know why this is not the case on your end ? I know that some merchants are renaming the field names in the database so lookup the id based on Name could lead to problems as well.

Regards,
Rik

**Comment by rikterbeek** [comment]
Let us know if there are still issues or fixes that are generic that we can implement.
Closing this issue for now.

Regards,
Rik
Adyen
