### ISSUE TITLE
HPP methods cannot be enumerated (listed)

### ISSUE THREAD

**Issue by ebaschiera** [Adyen/adyen-magento#603]
Hi,
HPP methods, being dynamic methods, cannot be enumerated by other modules, preventing interaction with them.
Some of HPP methods (well, actually all those don't have a proper model class) do not appear in the list generated by Mage_Payment_Helper_Data::getPaymentMethods(). For example: "adyen_hpp_directEbanking" and "adyen_hpp_bcmc".
This is a big problem for other extensions that rely on Mage_Payment_Helper_Data::getPaymentMethods() to perform actions on payments.
As an example, the module RicoNeitzel_PaymentFilter performs a whitelisting-based filter on payments. Being unable to display adyen_hpp_directEbanking and adyen_hpp_bcmc in the payment method list, they cannot be whitelisted and they get filtered out.
As another example, we use a similar approach to perform deferred capture on transactions. Payments with adyen_hpp_directEbanking and adyen_hpp_bcmc cannot be handled by our extension.
A solution to this issue may be to write a model class for each HPP payment method, or to overwrite Mage_Payment_Helper_Data::getPaymentMethods() to provide all HPP payment methods.

Thank you!
-Ermanno Baschiera

**Comment by rikterbeek** [comment]
Hi @ebaschiera,

We offer 250 different payment methods so that is why we created a dynamic payment method. They all use the adyen_hpp class (instead of ideal because of extra bank selection) could you just not add a extra sub selection on the payment method we save this in the cc_type column of the payment.

Regards,
Rik
Adyen

**Comment by ebaschiera** [comment]
Hi Rik,
my problem is not related to orders, but to magento configuration. That's why I am in need of a comprehensive list of payment methods. That list is needed by other modules to - for example - filter payment methods in checkout based on customer groups.
Anyway I managed to declare some "static" HPP methods only in Admin store view, just to make them appear in the payment method list.
Thank you!

**Comment by rikterbeek** [comment]
Hi @ebaschiera,

I understand your issue but because it is all dynamic this is not possible. It could be an option that you tweak the other modules so they can do a subselect on payment type instead of payment method.

Regards,
Rik
Adyen
