### ISSUE TITLE
Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details

### ISSUE THREAD

**Issue by sanutryzens** [Adyen/adyen-magento#629]
Hi Rik,

We are getting daily 2-3 error messages which saying the below trace on the log

2016-07-13T03:56:28+00:00 ERR (3): Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2683.0 Safari/537.36
2016-07-13T03:56:28+00:00 ERR (3): 
exception 'Adyen_Payment_Exception' with message 'Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details' in app/code/community/Adyen/Payment/Exception.php:42
Stack trace:
#0 app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php(243): Adyen_Payment_Exception::throwException('Missing the enc...')
#1 app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(276): Adyen_Payment_Model_Adyen_Data_PaymentRequest->create(Object(Mage_Sales_Model_Order_Payment), 43.87, 'cc', 'XXXXX...', 'ONECLICK', 'ONECLICK', 1)
#2 app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(191): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Mage_Sales_Model_Order_Payment), 43.87, 'authorise')
#3 app/code/core/Mage/Sales/Model/Order/Payment.php(1089): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Mage_Sales_Model_Order_Payment), 43.87)
#4 app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 43.87)
#5 app/code/core/Mage/Sales/Model/Order.php(898): Mage_Sales_Model_Order_Payment->place()
#6 app/code/core/Mage/Sales/Model/Order.php(1116): Mage_Sales_Model_Order->_placePayment()
#7 [internal function]: Mage_Sales_Model_Order->place()
#8 app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#9 app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#10 app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#11 app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#12 app/code/core/Mage/Checkout/Model/Type/Onepage.php(812): Mage_Sales_Model_Service_Quote->submitAll()
#13 app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#14 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#15 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#16 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#17 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#18 app/Mage.php(684): Mage_Core_Model_App->run(Array)
#19 index.php(19): Mage::run('jj_en_usd', 'store', Array)
#20 {main}

This is not happening for all orders, only some of the orders are getting affected by this issue.

**Comment by rikterbeek** [comment]
Hi @sanutryzens,

For creditcard we now have a static field created for cse to solve some issues. We need to do this for oneclick as well. Will try to implement this tomorrow so we can check if that solves your issues.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
@sanutryzens,

Could you check if this code change will solve your issues ?

Regards,
Rik
Adyen

**Comment by ebaschiera** [comment]
Me too I saw that error. The customer was on Safari+iPhone.
I will try your commit soon.

**Comment by sanutryzens** [comment]
Hello Rik,

Thanks a lot for you patch, it works perfectly for the mentioned error messages. The error is no more happening last few days and consider that is resolved.
However we are now having another payment failure message/email which saying 
>Reason: validation 174 Unable to decrypt data.

Below is the error log
2016-07-30T05:13:06+00:00 ERR (3): 
SoapFault exception: [soap:Server] validation 174 Unable to decrypt data in app/code/community/Adyen/Payment/Model/Adyen/Abstract.php:278
Stack trace:
#0 app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(278): SoapClient->__call('authorise', Array)
#1 app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(278): SoapClient->authorise(Array)
#2 app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(191): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Mage_Sales_Model_Order_Payment), 28.55, 'authorise')
#3 app/code/core/Mage/Sales/Model/Order/Payment.php(1089): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Mage_Sales_Model_Order_Payment), 28.55)
#4 app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 28.55)
#5 app/code/core/Mage/Sales/Model/Order.php(898): Mage_Sales_Model_Order_Payment->place()
#6 app/code/core/Mage/Sales/Model/Order.php(1116): Mage_Sales_Model_Order->_placePayment()
#7 [internal function]: Mage_Sales_Model_Order->place()
#8 app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#9 app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#10 app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#11 app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#12 app/code/core/Mage/Checkout/Model/Type/Onepage.php(812): Mage_Sales_Model_Service_Quote->submitAll()
#13 app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#14 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#15 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#16 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#17 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#18 app/Mage.php(684): Mage_Core_Model_App->run(Array)
#19 en-us/index.php(19): Mage::run('jj_en_usd', 'store', Array)
#20 {main}

Could you please assist me to solve this issue.

Kind Regards
Sanu

**Comment by rikterbeek** [comment]
Hi @sanutryzens,

This issue should be solved in 2.7.0 and you are using native magento checkout.
Let me know if this issue is solved on your side as well ?

Regards,
Rik
Adyen

**Comment by sanutryzens** [comment]
Hello Rik,

Thanks for the update. The issue already resolved with your patch. So release 2.7.0 should be fine for this issue. But please see my comment https://github.com/Adyen/adyen-magento/issues/629#issuecomment-237782642 we have one another last issue, which different from this one.

Thanks
Sanu

**Comment by rikterbeek** [comment]
Hi @sanutryzens,

That is the same issue we only did not set the exception anymore. Are you using some external checkout module ?

Regards,
Rik
Adyen

**Comment by sanutryzens** [comment]
no, the native magento checkout itself. I think this exception message is coming as adyen api result

**Comment by rikterbeek** [comment]
correct but only will occur when CSE is not provided or you using a wrong CSE key.
Can you let us know for what reference(increment_id in magento) the payment failed. Best to send a ticket to magento@adyen.com.

Regards,
Rik
Adyen

**Comment by tieroom** [comment]
We updated our adyen module to 2.7.1 last week. This seems to have solved a previous issue ("validation 174 Unable to decrypt data") but introduced the new issue as in this ticket. Does not occur on every order, maybe on one in 30 or so.

We are on php 5.5.29, magento 1.9.2.2 and run Firecheckout 3.7.0.

**Comment by benzi1984** [comment]
Althea is also facing this issue with CSE intermittently. 
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/18161698/18872383/7d55fc86-84ba-11e6-995a-2f17b54b901d.jpg)

Plugin Version: 2.7.1

One of the users affected was an internal employee. He was using Windows 10 Home Edition, Google Chrome Version 53.0.2785.116. 

One-Step-Checkout: MageGiant

**Comment by rikterbeek** [comment]
Hi @benzi1984,

Did they look into the MageGiant checkout could be a problem with this external checkout module.

Regards,
Rik
Adyen
