### ISSUE TITLE
Openinvoice: field.billto.housenumber.invalid

### ISSUE THREAD

**Issue by oblomovx** [Adyen/adyen-magento#637]
When a customer tries to order with the openinvoice method and uses a housenumber with an addition (25 1 for example), the following error is shown in the backend and the order is cancelled:

Raw acquirer response: 2 : Geweigerd - validatie : Failure= shipto.housenumber: field.shipto.housenumber.invalid, billto.housenumber: field.billto.housenumber.invalid

**Comment by rikterbeek** [comment]
Hi @oblomovx,

Could you provide a pspReference number for us so we can check what is going wrong ? looks like the request is refused by the acquirer. For this matters best to contact our support at support@adyen.com.

Regards,
Rik

**Comment by oblomovx** [comment]
psp reference: 1314702199213407

**Comment by rikterbeek** [comment]
Hi @oblomovx,

We sending this to afterpay:

<billingAddress>
<houseNumberOrName xmlns="http://common.services.adyen.com">25 1</houseNumberOrName>
...

and 

<deliveryAddress>
<houseNumberOrName xmlns="http://common.services.adyen.com">25 1</houseNumberOrName>
....

Please contact Afterpay why they do not accept this.

Regards,
Rik
Adyen
