### ISSUE TITLE
Orders remain in pending after offer is closed

### ISSUE THREAD

**Issue by benzi1984** [Adyen/adyen-magento#642]
Hi Team, 

This issue was raised separately by a merchant, but I did some digging and perhaps we can make an improvement here.

For some alternative payments, customers will be redirected to those APM's website. The customer may drop off there, so this leaves an open offer on our Adyen system without a payment. The customer can come back to complete the payment, but most times, the customer does not, and after a certain time, our system will close the offer. When that happens, our notification system will send out an OFFER_CLOSED notification. This is read by our Magento plugin (see attached screenshot), but this "OFFER_CLOSED" is not processed in "ProcessNotification.php". Neither is it enumerated in "app/code/community/Adyen/Payment/Model/Event.php"

We should see how we can read in this status and update the Magento order accordingly. Thanks!

![image](https://cloud.githubusercontent.com/assets/18161698/17580655/e4241946-5fd2-11e6-80e3-82c6a68d06a1.png)

**Comment by rikterbeek** [comment]
Hi @benzi1984,

OFFER_CLOSE is not by default turned on. I will do some investigation if we can cancel the order when this notification is received.

Regards,
Rik
Adyen

**Comment by rogan-son** [comment]
Hi,

Can I know the status of this issue?

Thanks,
Rogan
