### ISSUE TITLE
error in logs: Zend_Json_Exception: Decoding failed: Syntax error in /lib/Zend/Json.php:97

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/adyen-magento#643]
2016-08-03T20:07:32+00:00 ERR (3): 
Zend_Json_Exception: Decoding failed: Syntax error in /lib/Zend/Json.php:97
Stack trace:
#0 /app/code/core/Mage/Core/Helper/Data.php(659): Zend_Json::decode('', 1)
#1 /app/code/core/Mage/Persistent/Model/Session.php(133): Mage_Core_Helper_Data->jsonDecode(NULL)
#2 /app/code/core/Mage/Core/Model/Abstract.php(226): Mage_Persistent_Model_Session->_afterLoad()
#3 /app/code/core/Mage/Persistent/Model/Session.php(154): Mage_Core_Model_Abstract->load('deleted', 'key')
#4 /app/code/core/Mage/Persistent/Helper/Session.php(67): Mage_Persistent_Model_Session->loadByCookieKey()
#5 /app/code/core/Mage/Persistent/Helper/Session.php(91): Mage_Persistent_Helper_Session->getSession()
#6 /app/code/core/Mage/Persistent/Model/Observer.php(417): Mage_Persistent_Helper_Session->isPersistent()
#7 /app/code/core/Mage/Persistent/Model/Observer.php(427): Mage_Persistent_Model_Observer->_isPersistent()
#8 /app/code/core/Mage/Persistent/Model/Observer.php(437): Mage_Persistent_Model_Observer->_isLoggedOut()
#9 /app/code/core/Mage/Persistent/Model/Observer.php(229): Mage_Persistent_Model_Observer->_isGuestShoppingCart()
#10 /app/code/core/Mage/Core/Model/App.php(1358): Mage_Persistent_Model_Observer->setLoadPersistentQuote(Object(Varien_Event_Observer))
#11 /app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Persistent_Model_Observer), 'setLoadPersiste...', Object(Varien_Event_Observer))
#12 /app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('custom_quote_pr...', Array)
#13 /app/code/core/Mage/Checkout/Model/Session.php(118): Mage::dispatchEvent('custom_quote_pr...', Array)
#14 /app/code/community/Adyen/Payment/Model/Observer.php(177): Mage_Checkout_Model_Session->getQuote()
#15 /app/code/community/Adyen/Payment/Model/Observer.php(241): Adyen_Payment_Model_Observer->_getQuote()
#16 /app/code/community/Adyen/Payment/Model/Observer.php(117): Adyen_Payment_Model_Observer->_getCurrentPaymentAmount()
#17 /app/code/community/Adyen/Payment/Model/Observer.php(64): Adyen_Payment_Model_Observer->_fetchHppMethods(Object(Mage_Core_Model_Store))
#18 /app/code/community/Adyen/Payment/Model/Observer.php(45): Adyen_Payment_Model_Observer->_addHppMethodsToConfig(Object(Mage_Core_Model_Store))
#19 /app/code/core/Mage/Core/Model/App.php(1358): Adyen_Payment_Model_Observer->addMethodsToConfig(Object(Varien_Event_Observer))
#20 /app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Adyen_Payment_Model_Observer), 'addMethodsToCon...', Object(Varien_Event_Observer))
#21 /app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#22 /app/code/core/Mage/Core/Controller/Varien/Action.php(527): Mage::dispatchEvent('controller_acti...', Array)
#23 /app/code/core/Mage/Core/Controller/Front/Action.php(69): Mage_Core_Controller_Varien_Action->preDispatch()
#24 /app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Core_Controller_Front_Action->preDispatch()
#25 /app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('redirect')
#26 /app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#27 /app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#28 /app/Mage.php(683): Mage_Core_Model_App->run(Array)
#29 /index.php(86): Mage::run('lfl_nl', 'store')
#30 {main}
 </body>
</html>

**Comment by rikterbeek** [comment]
Hi,

This error message is trown because it is trying to json_decode an empty string.
I am not sure if this is coming from our module because I can see the observer custom_quote_pr.. is called. 
#12 /app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('custom_quote_pr...', Array)

Do you have a observer on this with manual code ?

Regards,
Rik
Adyen
