### ISSUE TITLE
Order Status remains pending and adyen status is N.A. even the payment has been captured

### ISSUE THREAD

**Issue by olivercastro** [Adyen/adyen-magento#650]
What could have caused this issue?

Customer Notification Not Applicable 
Captured amount of $100.00 online.

Customer Not Notified 
Adyen Result URL Notification(s): 
authResult: AUTHORISED 

Customer Not Notified 
Adyen Result URL Notification(s): 
authResult: AUTHORISED 

Aug 1, 2016 6:01:01 PM|Pending
Customer Notified  

Is this an isolated scenario and how can we prevent it?

**Comment by rikterbeek** [comment]
HI @olivercastro,

Looks like your notifications are not working or you do not have your magento cron running.
See our documentation about notification and cronjob setup:
* https://docs.adyen.com/developers/magento#preparethesettingsintheadyencustomerarea
* https://docs.adyen.com/developers/magento#configuretheadyenplugin

Regards,
Rik

**Comment by olivercastro** [comment]
This issue occurs only to one particular order and the rest were working before

**Comment by rikterbeek** [comment]
Hi @olivercastro,

Where did it go wrong ? did you receive the notification ? Check the log files what the notification did on your platform and to see where it did go wrong.

Regards,
Rik
Adyen

**Comment by fullenglish** [comment]
Our orders were saving to processing with exactly the same Magento settings, until we updated to the latest release, now they authorise but are saving as pending and not processing ? Any ideas please ?

**Comment by rikterbeek** [comment]
Hi @fullenglish,

Did you solve your issues. This is just configurable by the notifications system. Please let us know on magento@adyen.com if you have any questions regarding the configuration of this.

Regards,
Rik
Adyen
