### ISSUE TITLE
Issue with refused payment, reserved increment ID not reset

### ISSUE THREAD

**Issue by EliasZ** [Adyen/adyen-magento#654]
### Situation

Customer returns at the validate3d process (`ProcessController::validate3dAction`), and the authorization is handled. The response code is "Refused". An order ID has been reserved, but it is not being reset resulting in `Duplicate entry 'XXXX' for key 'UNQ_SALES_FLAT_ORDER_INCREMENT_ID'` errors whenever payment is attempted again.
### Stack trace

```
#0 /vendor/adyen/payment/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(449): Adyen_Payment_Exception::throwException('The payment is ...')
229
#1 /vendor/adyen/payment/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(341): Adyen_Payment_Model_Adyen_Abstract->_processResponse(Object(Mage_Sales_Model_Order_Payment), Object(stdClass), 'authorise3d')
#2 /vendor/adyen/payment/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(229): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Mage_Sales_Model_Order_Payment), '49.0000', 'authorise3d')
#3 /vendro/adyen/payment/app/code/community/Adyen/Payment/controllers/ProcessController.php(203): Adyen_Payment_Model_Adyen_Abstract->authorise3d(Object(Mage_Sales_Model_Order_Payment), '49.0000')
#4 /magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Adyen_Payment_ProcessController->validate3dAction()
[...]
```
### The issue

On line 449 of  `Adyen_Payment_Model_Adyen_Abstract`, the exception is thrown. On the previous line `resetReservedOrderId()` is called, but the quote is never saved in that method. This also happens in the `cancel()` of the `ProcessController` where `setReservedOrderId(null)` is called on the quote, but never saved.

---

We could not test it with an additional call to `save()` on the quote, as it is not clear how to generate a specific response in Adyen test mode.

version: 2.6.3 and #626 cherry picked

**Comment by rikterbeek** [comment]
Hi @EliasZ,

I think this is a bug in the magento core system. Can you check if this:
http://stackoverflow.com/questions/27303536/magento-sqlstate23000-integrity-constraint-violation-1062-duplicate-entry
Solves your issue ?


Regards,
Rik
