### ISSUE TITLE
Adyen CSE compatibility with Ecomdev_Checkitout

### ISSUE THREAD

**Issue by bramvanderholst** [Adyen/adyen-magento#657]
CSE is currently not working in Ecomdev_Checkitout.
In app/design/frontend/base/default/template/adyen/form/cc.phtml:310 the 'payment[encrypted_data]' field is created inside the form element.

Ecomdev disables any field outside of the active '.panel-sp-method' element within the form, which causes payment[encrypted_data] to not be included in the post data.

The following fixes that problem;
https://cl.ly/382P2t1x1g0O

**Comment by rikterbeek** [comment]
Hi @bramvanderholst,

Thanks for letting us know! Would you be able to do  a PR to our develop branch for these code changes ? Please change the JQuery part to prototype because that is supported out of the box in Magento1.

Regards,
Rik
Adyen

**Comment by paales** [comment]
Hi @rikterbeek,

Could you tackle the prototype stuff your selves. We've run out of time to declare to our client :)

```DIFF
diff --git a/app/design/frontend/bootstrap/default/template/adyen/form/cc.phtml b/app/design/frontend/bootstrap/default/template/adyen/form/cc.phtml
index 1030f05..dd37d34 100644
--- a/app/design/frontend/bootstrap/default/template/adyen/form/cc.phtml
+++ b/app/design/frontend/bootstrap/default/template/adyen/form/cc.phtml
@@ -329,7 +329,22 @@ $_code = $this->getMethodCode();
                 if (payment.currentMethod && payment.currentMethod == '<?php echo $_code ?>') {
                     var cseForm = adyen.encrypt.createEncryptedForm(form, cse_key, cse_options);
                     // encrypt data directly because submit button is not always on the page
-                    cseForm.createEncryptedField(cseForm.encrypt());
+                    if (EcomDev == 'undefined' && EcomDev.CheckItOut == 'undefined') {
+                        cseForm.createEncryptedField(cseForm.encrypt());
+                    } else {
+                        // Ecomdev_Checkitout disables fields outside of active .panel-sp-method
+                        // to prevent unnecessary fields being included in post data
+                        // therefore the input needs to be appended in the proper .panel-sp-method instead of at the end of the form element
+                        var elementName = 'payment[encrypted_data]';
+                        var element = document.getElementById(elementName);
+                        if (!element) {
+                            element = document.createElement('input');
+                            element.type = 'hidden';
+                            element.name = element.id = elementName;
+                            jQuery('[name="payment[method]"]:checked').parents('.panel-sp-method').find('.panel-body').append(element);
+                        }
+                        element.setAttribute('value', cseForm.encrypt());
+                    }
                 }
             } catch (e) {
                 if (typeof console == "object") {
```

**Comment by rikterbeek** [comment]
Hi @paales,

Sure, I can pick it up.

Regards,
Rik
Adyen

**Comment by paales** [comment]
Oh, now that I take a look at the information, I think the `.panel-sp-method` is specific to our custom frontend framework. The default EcomDev CheckItOut module uses different templates.

**Comment by rikterbeek** [comment]
Hi @paales,

Can you let me know what it is? Could you let me know who to contact from CheckItOut then maybe we can build it in for them so it will be compatible.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi All,

Should be compatible now with the CheckItOut extension.

Regards,
Rik
Adyen
