### ISSUE TITLE
Should payment errors like "Adyen_Payment_Exception: Le paiement a été refusé." appear in exception.log in /var?

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#658]
Should payment errors like "Adyen_Payment_Exception: Le paiement a été refusé." appear in exception.log in /var?

Is it a coding error?
A process error? 

Our tech dev is always surprised to find this here on our monthly rounds. And every once in a while we try to debug this - but every time we realize it is a functional process error (Of the user): hence, should it appear in except log?

2016-08-16T19:06:29+00:00 ERR (3): 
Adyen_Payment_Exception: Le paiement a été refusé. in app/code/community/Adyen/Payment/Exception.php:42
Stack trace:
#0 app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(436): Adyen_Payment_Exception::throwException('Le paiement a \xC3...')
#1 app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(328): Adyen_Payment_Model_Adyen_Abstract->_processResponse(Object(Mage_Sales_Model_Order_Payment), Object(stdClass), 'authorise')
#2 app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(191): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Mage_Sales_Model_Order_Payment), 196.11, 'authorise')
#3 app/code/core/Mage/Sales/Model/Order/Payment.php(1089): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Mage_Sales_Model_Order_Payment), 196.11)
#4 app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 196.11)
#5 app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#6 app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#7 app/code/core/Mage/Core/Model/Resource/Transaction.php(105): Mage_Sales_Model_Order->place()
#8 app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#9 app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#10 app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#11 app/code/core/Mage/Checkout/Model/Type/Onepage.php(812): Mage_Sales_Model_Service_Quote->submitAll()
#12 app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#13 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#14 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#15 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 app/Mage.php(683): Mage_Core_Model_App->run(Array)
#18 index.php(86): Mage::run('soc_fr', 'store')
#19 {main}
2016-08-16T19:39:17+00:00 ERR (3): 
Adyen_Payment_Exception: Le paiement a été refusé. in app/code/community/Adyen/Payment/Exception.php:42
Stack trace:
#0 app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(436): Adyen_Payment_Exception::throwException('Le paiement a \xC3...')
#1 app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(328): Adyen_Payment_Model_Adyen_Abstract->_processResponse(Object(Mage_Sales_Model_Order_Payment), Object(stdClass), 'authorise')
#2 app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(191): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Mage_Sales_Model_Order_Payment), 196.11, 'authorise')
#3 app/code/core/Mage/Sales/Model/Order/Payment.php(1089): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Mage_Sales_Model_Order_Payment), 196.11)
#4 app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 196.11)
#5 app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#6 app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#7 app/code/core/Mage/Core/Model/Resource/Transaction.php(105): Mage_Sales_Model_Order->place()
#8 app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#9 app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#10 app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#11 app/code/core/Mage/Checkout/Model/Type/Onepage.php(812): Mage_Sales_Model_Service_Quote->submitAll()
#12 app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#13 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#14 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#15 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 app/Mage.php(683): Mage_Core_Model_App->run(Array)
#18 index.php(86): Mage::run('soc_fr', 'store')
#19 {main}

**Comment by rikterbeek** [comment]
Hi @seansan,

Magento expect an exception so it can show a notice to the client that the payment failed. You have exception logging enabled so it will be logged.

Regards,
Rik
Adyen
