### ISSUE TITLE
order confirmation delay

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/adyen-magento#661]
Hi, I'd just like to report this again. We are getting quite some questions about orders not being confirmed immediately. With CC and Ideal payments are instant. And when a customer completes their order the almost immediately go to their inbox and see if they have an order confirmation. 

The problem is that with the adyen payments the confirmation is never there. It takes between 3 sometimes even 11 minutes before the email arrives. 

I think we should take some time to think about: how we can make this email almost instant. 

For discussions sake: it is the customer reporting this. it is their expectation (from experience /w other medium/big stores). And currently we have about 10-15 emails per week that we get a question about this: where is my order confirmation (so the customer emails within the 3-11 minute timeframe before the order email is sent)

**Comment by rikterbeek** [comment]
Hi @shirtsofholl,

The mail sending is done by Magento itself. If the AUTHORISATION notification is processed we tell Magento to send out the order confirmation mail. Keep in mind that our notification processing and magento mail sending are processed by cronjobs. Make sure your magento cronjob is running every minute and make sure the email cronjob of magento is set to every minute as well. Our module is already doing that.

Regards,
Rik
Adyen
