### ISSUE TITLE
ADYEN_EVENT_MANUAL_REVIEW_REJECT should cancel the order

### ISSUE THREAD

**Issue by ebaschiera** [Adyen/adyen-magento#662]
Hi,
in Model/ProcessNotification.php when the code checks for Adyen_Payment_Model_Event::ADYEN_EVENT_MANUAL_REVIEW_REJECT, there is a comment stating: "don't do anything it will send a CANCEL_OR_REFUND notification when this payment is captured".
I disagree with that. When that payment is captured, Magento probably is also creating an invoice, which cannot be canceled afterwards.
So the correct behaviour, IMHO, should be that when an ADYEN_EVENT_MANUAL_REVIEW_REJECT notification arrives, the order should be canceled right away.

Thanks for reading! :)
Best regards.

**Comment by rikterbeek** [comment]
Hi @ebaschiera,

There is a mistake in the comment it should be "don't do anything it will send a CANCEL_OR_REFUND notification when this payment is cancelled". If this notification is received there will always be a CANCELLED or CANCELLATION notitifcation from our platform. You can see in the code that if this is received the order will be cancelled.

Regards,
Rik
Adyen
