### ISSUE TITLE
Add Pre-order functionality

### ISSUE THREAD

**Issue by rikterbeek** [Adyen/adyen-magento#670]

**Comment by franzludilabel** [comment]
Hi,
Can you explain what this pre-order functionality is ?
Cant find any documentation about it
Thank you :)

**Comment by rikterbeek** [comment]
Hi @franzludilabel,

Correct it is not an plug and play solution. You can now define a product a pre-order and will taken into the order itself. There is no additional logic yet.
https://github.com/Adyen/adyen-magento/pull/671/files

Regards,
