### ISSUE TITLE
Updated to 2.7.1 - new issue with status/state

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/adyen-magento#673]
Updated to 2.7.1 - new issue with status/state

Previously there was a difference between 'time lagged' payments and immediate payments and the way they pass through state/status

ideal payments that are pending => are closed after 30 minutes and stock is released
payment requests by email that are pending => are closed after 5 days and stock is released

Ideal we targeted by state: pending_payment and status: pending_payment
Payment link we targeted by state: pending_payment and status: pending
in table sales_flat_order

since the update to 2.7.1 we see that all Payment links are closed within 30 minutes => apparently the rule for Ideal is also now triggering the Payment link payments : this is not correct

There should be a difference in status between these two. 1 takes a lot more time than the other. Ideal payments that do not occur within 5 minutes can be considered as abandoned, whilst for pay by email links this it not! the case

![image](https://cloud.githubusercontent.com/assets/11224809/18586315/63c2d9fc-7c1c-11e6-8e51-f546d89acfaf.png)

**Comment by shirtsofholl** [comment]
A solution would be to join sales_flat_order_payment, sales_flat_order and adyen_order_payment so order_id | state | status | payment_method are seen in 1 collection. Then we can check for both columsn2,3 and 4 ..... but:

- this used to work before based on state and status (and did so with previous PSP's)
- then we need a whole array of payment_methods to check for .... all the different CC cards etc

A. Slow methods: bank_transfer + sepa_debit + payment
and 
B. Fast methods: Creditcard + Ideal + other

Should be discernible

**Comment by rikterbeek** [comment]
Hi @shirtsofholl,

We do not close payments after 30min think this is a cusom script doing that for you. What you can do is look at the payment method and do not close the pay_by_mail payement method after 30 minutes but after 5 days. Make sure that the payment link is not working as well after 5 days otherwise you get some problems.

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
I know you dont close payments; we do

the difference is here

pay_by_email should have a similar status as banktransfer

![image](https://cloud.githubusercontent.com/assets/11224809/18587315/afa4c042-7c21-11e6-8f90-17e042218405.png)

**Comment by rikterbeek** [comment]
Hi @shirtsofholl,

This status can be controlled by you by setting the setting "Order status: order creation".

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
you mean this one

but is this setting then for

A. Slow methods: bank_transfer + sepa_debit + payment
or
B. Fast methods: Creditcard + Ideal + other
or
both A + B

this question is about how we can distinguish between A and B

![image](https://cloud.githubusercontent.com/assets/11224809/18587787/ecf0f7f2-7c23-11e6-891d-93a93809b3ea.png)

**Comment by rikterbeek** [comment]
Hi @shirtsofholl,

You can distinguish them by payment method.

Regards,
Rik
Adyen

**Comment by shirtsofholl** [comment]
hmm feels we are running in circles ... just know that payment_email never
caused a problem before

and that we think it is important to distinguish between
- slow payments
- direct payments

filter on all the different payment labels that exist of course can be
done, but
- there are so many, and many new ones can be added over time
- they might change names

this is why a state | status like
pending_payment | pending => direct payments
pending_payment | pending_payment => direct payments

or anything that would make one be able to discern between the two

would be excellent

I hope you understand the business need of this / understand our request










Wij maken het graag voor je in orde.

ps. heb je vragen of wil je overleggen? Bel ons gelijk: +31 20 2331695
(ma-zat tussen 9.00 en 17.00)

met groeten, Mark


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | https://shirtsofholland.com

[image: Oranje overhemden, oranje shirts en oranje kleding met typische
Nederlandse en Hollandse details voor Koningsdag, WK Hockey en WK voetbal.
✓ De beste kwaliteit. ✓ De beste service.]

2016-09-16 15:42 GMT+02:00 Rik ter Beek <notifications@github.com>:

**Comment by rikterbeek** [comment]
Hi @shirtsofholl,

The only way to distinguish payment methods that need more time for authorization is the payment method in combination with the status. I advise you to add a check what payment method is selected in your cancellation script.

Regards,
Rik
Adyen
