### ISSUE TITLE
All payments goes "suspected fraud" for a few seconds, before change to "processing"

### ISSUE THREAD

**Issue by elfeffe** [Adyen/adyen-magento#678]
All the payments says "Suspected fraud" for a few seconds. Then they go correctly to "processed".
The problem is that some customers complaints about this, of course.
That must be a bug.

Any solution for this?

**Comment by rikterbeek** [comment]
Hi @elfeffe,

Think you need to set Payment Review as the default status for payment_review instead of Suspected fraud.

Regards,
Rik
Adyen

**Comment by elfeffe** [comment]
You mean this setting?
https://gyazo.com/fe928e5a497deb0d97e487b992f6c778
If yes, is set to nothing by default.
Can that be the problem?

**Comment by elfeffe** [comment]
Or you mean this one

https://gyazo.com/836fd3d0623b8c9bd6a9e7f33bb6a472

**Comment by rikterbeek** [comment]
Hi @elfeffe,

I mean your last reply.

Regards,
Rik
Adyen
