### ISSUE TITLE
Credit card fails after SUPEE-8788 patch

### ISSUE THREAD

**Issue by oblomovx** [Adyen/adyen-magento#681]
After the SUPEE-8788 patch, credit card payments fail. The following exception is thrown

`2016-10-13T17:12:06+00:00 ERR (3): 
exception 'Adyen_Payment_Exception' with message '3D secure went wrong for orderId: 23804 adyenStatus is: RedirectShopper' in /data/web/public/app/code/community/Adyen/Payment/Exception.php:42
Stack trace:
#0 /data/web/public/app/code/community/Adyen/Payment/controllers/ProcessController.php(255): Adyen_Payment_Exception::throwException('3D secure went ...')
#1 /data/web/public/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Adyen_Payment_ProcessController->validate3dAction()
#2 /data/web/public/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('validate3d')
#3 /data/web/public/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#4 /data/web/public/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#5 /data/web/public/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#6 /data/web/public/index.php(88): Mage::run('base', 'website')
#7 {main}`

**Comment by rikterbeek** [comment]
Hi @oblomovx,

RedirectShopper means the card was enrolled to 3D secure page of the bank. I did some test with our module and the latest magento patch but could not see any problems. Maybe this shopper did something weird on his end could you ask him the steps that were taken ?

Regards,
Rik
Adyen

**Comment by oblomovx** [comment]
Hi @rikterbeek 

We have seen this with 4 orders on 2 installations with Adyen version 2.6.3 . We had a problem that might be related with this with the hash_equals function.

**Comment by rikterbeek** [comment]
Hi @oblomovx,

the error is thrown here:
https://github.com/Adyen/adyen-magento/blob/develop/app/code/community/Adyen/Payment/controllers/ProcessController.php#L249-L259

meaning that the if statement is failed. It looks like data is not received from the 3D secure payment:
https://github.com/Adyen/adyen-magento/blob/develop/app/code/community/Adyen/Payment/controllers/ProcessController.php#L188

Could you send a ticket to magento@adyen.com with the reference and timestamp and you webserver user then we can check our logs what we have done unfortunately we can't see the result from the bank to your side so you may want to add some extra logging on the exact result.

Regards,
Rik

**Comment by oblomovx** [comment]
This issue was resolved by the updated Magento patch for supee-8788 https://magento.com/security/patches/supee-8788

**Comment by rikterbeek** [comment]
Hi @oblomovx,

Great!

Regards,
Rik
Adyen
