### ISSUE TITLE
Support for IDIN https://www.idin.nl/

### ISSUE THREAD

**Issue by shirtsofholl** [Adyen/adyen-magento#695]
Support for IDIN https://www.idin.nl/

https://www.idin.nl/acceptanten/

PSP is only party who can realistically do this

and would be cutting edge ;)

**Comment by rikterbeek** [comment]
Hi @shirtsofholl,

Had a brief overview and it looks like it does not have a strong focus for ecommerce but more focussing on verify the shopper identity for agencies. I have our local payments team informed and they keep this in mind. For more information and questions about this you can ask it at support@adyen.com. This is more platform related then it concerns our extension. If it be available on our platform ofcourse it will be in our module as well. 

Regards,
Rik
Adyen

**Comment by seansan** [comment]
ING launched a news release yesterday saying they fully support https://www.betaalvereniging.nl/giraal-en-online-betalen/idin/

Also for eCommerce

The major interesting part is that someone can identify him/herself + also obtain address details in 1 go

meaning one could go to the checkout, confirm identity and address and payment all in step

Maybe someting similar to Paypal express
