### ISSUE TITLE
CSE support for alternative checkout modules

### ISSUE THREAD

**Issue by lancergr** [Adyen/adyen-magento#698]
On some alternative checkout modules, the javascript **payment** object does not exists and this causes CSE javascript library to fail and not generate the encrypted_data field.

The following error message was presented:
"Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details"

**Comment by tieroom** [comment]
Is 2.8.1 or (2.8.0.1) to be officially released soon so we can apply this fix? Or would it be safe to apply the development branch?

**Comment by lancergr** [comment]
Hi @tieroom ,

We plan to release 2.8.1 and include this fix to it on the upcoming days.

I wouldn't recommend to apply the development branch yet.

Best Regards,
Giorgos Adam
Adyen

**Comment by lancergr** [comment]
Hi @tieroom 

The version 2.8.1 is just released.


Kind Regards,
Giorgos Adam
Adyen

**Comment by tieroom** [comment]
Awesome! Thannks @lancergr, will install tomorrow.

**Comment by tieroom** [comment]
Been running 2.8.1 for a while now and can, unfortunately, confirm the issue still exists. We're on magento 1.9.2.2 and, more importantly, firecheckout 3.10.0 which I'm guessing is what somehow doesn't play well with the encryption code.

The error still occurs intermittently with maybe one in 50-100 orders being affected and most of these going through after a couple of retries.

Let me know if there is any other info you need to debug. Also, I can hook you up with the firecheckout developers who tend to be very cooperative at bug finding and ensuring they integrate with all payment methods.

**Comment by rikterbeek** [comment]
Hi @tieroom,

If you can contact the developer of firecheckout  to share the module with us we can have a closer look. But if it only happens 50-100 orders it will be diffecult for us to reproduct. You can contact us directly on magento@adyen.com

Regards,
Rik
Adyen
