### ISSUE TITLE
Notice: unserialize(): Error at offset 0 of 4 bytes

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#705]
dont remember if reported before, but seeing this in pre-last version in logs

2016-11-24T08:20:02+00:00 ERR (3): Notice: unserialize(): Error at offset 0 of 4 bytes  in /var/www/html/web/public_html/app/code/community/Adyen/Payment/Block/Form/Abstract.php on line 77

**Comment by sandermangel** [comment]
In `2.8.0` this is caught 

```php
if (is_null($this->_paymentData)) {
   $payment = $this->_getQuote()->getPayment();
   try {
      $this->_paymentData = unserialize($payment->getPoNumber());
   } catch (Exception $e) {
      $this->_paymentData = array();
   }
}
```

**Comment by rikterbeek** [comment]
Hi @sandermangel ,

Thanks for sharing this. @seansan please upgrade to latest version to solve this issue.

Regards,
Rik
Adyen
