### ISSUE TITLE
Changing input type from text to number for credit card

### ISSUE THREAD

**Issue by vedransola** [Adyen/adyen-magento#710]
Having numerical keyboard on the mobile would be a very good UX improvement.

**Comment by shanelja** [comment]
Obviously the official decision is for the Adyen team, but I'm not sure this should happen - I agree it would be a good UX improvement but it's only supported by HTML5, not all stores using the Adyen module use HTML5, some use XHTML still where this input type isn't supported [1], so it's likely to break some people's workflows, especially if they're using strict mode.

[1] - https://www.w3.org/TR/html5-diff/#new-elements

**Comment by siggi-hs** [comment]
I think it would be harmless.

If the browser doesn’t support new attributes such as `type=“number”`, it will simply fallback to `type=“text”`.

It would be perfect if retailers had the option to add the new attributes themselves.
That way older stores don’t have to worry about their stuff breaking and new stores can take advantage of modern browsers.

**Comment by shanelja** [comment]
@siggi-hs if that's the fallback, I can't see any issue with it at all. Support. 👍

**Comment by rikterbeek** [comment]
Hi @vedransola,

Thanks for letting us know about this approvement and thanks all for the reactions. See commit below using type="number" for the fields that only allows numbers.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi,

This will break our javascript that is running on the background that add spaced between the numbers for a better overview. I found a better solution instead of type="number" it is better to use type="text" pattern="[0-9]*" you can see now on the mobile you can only fill in a number and showing the number pad instead of the full keyboard.

Regards,
Rik
Adyen

**Comment by shanelja** [comment]
Hi all, further to @rikterbeek's commit, I've added the following PR to refine the filters used, if we're adding the filters to (already required) fields, we may as well use them for validation as well: https://github.com/Adyen/adyen-magento/pull/715

**Comment by shanelja** [comment]
@vedransola This has been merged in to the develop branch, are you happy with the issue resolution?

**Comment by vedransola** [comment]
@shanelja This is perfect, thanks!

**Comment by rikterbeek** [comment]
Hi All,

This is included into the latest release version.

Regards,
Rik
Adyen
