### ISSUE TITLE
Misplaced characters in the Adyen/Fee module config.xml

### ISSUE THREAD

**Issue by sandermangel** [Adyen/adyen-magento#711]
https://github.com/Adyen/adyen-magento/blob/master/app/code/community/Adyen/Fee/etc/config.xml

In the config.xml there are 2 characters misplaced at the bottom `</sales>xw` that will cause issues with loading the XML (invalidating it)

**Comment by shanelja** [comment]
@sandermangel a bug fix release for this will happen later today by @rikterbeek, thanks for flagging it.

**Comment by sandermangel** [comment]
@shanelja np, thanks for the quick fix, already patched it locally :)
