### ISSUE TITLE
Still happens sometimes latest version

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#712]
Still happens sometimes latest version. Not a lot of info to go by. But still happens sometimes. 

Adyen_Payment_Exception: Missing the encrypted data value

2016-12-10T02:37:43+00:00 ERR (3): 
Adyen_Payment_Exception: Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details in /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Exception.php:42
Stack trace:
#0 /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php(253): Adyen_Payment_Exception::throwException('Missing the enc...')
#1 /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(359): Adyen_Payment_Model_Adyen_Data_PaymentRequest->create(Object(Mage_Sales_Model_Order_Payment), 99.95, 'cc', 'domainofHolland...', 'ONECLICK', 'RECURRING', 0)
#2 /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(267): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Mage_Sales_Model_Order_Payment), 99.95, 'authorise')
#3 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order/Payment.php(1089): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Mage_Sales_Model_Order_Payment), 99.95)
#4 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 99.95)
#5 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#6 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#7 /var/www/html/domain/public_html/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): Mage_Sales_Model_Order->place()
#8 /var/www/html/domain/public_html/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#9 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#10 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#11 /var/www/html/domain/public_html/app/code/core/Mage/Checkout/Model/Type/Onepage.php(815): Mage_Sales_Model_Service_Quote->submitAll()
#12 /var/www/html/domain/public_html/app/code/core/Mage/Checkout/controllers/OnepageController.php(578): Mage_Checkout_Model_Type_Onepage->saveOrder()
#13 /var/www/html/domain/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#14 /var/www/html/domain/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#15 /var/www/html/domain/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /var/www/html/domain/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 /var/www/html/domain/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#18 /var/www/html/domain/public_html/index.php(83): Mage::run('ovh_nl', 'store')
#19 {main}
2016-12-10T02:37:54+00:00 ERR (3): 
Adyen_Payment_Exception: Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details in /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Exception.php:42
Stack trace:
#0 /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php(253): Adyen_Payment_Exception::throwException('Missing the enc...')
#1 /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(359): Adyen_Payment_Model_Adyen_Data_PaymentRequest->create(Object(Mage_Sales_Model_Order_Payment), 99.95, 'cc', 'domainofHolland...', 'ONECLICK', 'RECURRING', 0)
#2 /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(267): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Mage_Sales_Model_Order_Payment), 99.95, 'authorise')
#3 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order/Payment.php(1089): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Mage_Sales_Model_Order_Payment), 99.95)
#4 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 99.95)
#5 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#6 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#7 /var/www/html/domain/public_html/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): Mage_Sales_Model_Order->place()
#8 /var/www/html/domain/public_html/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#9 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#10 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#11 /var/www/html/domain/public_html/app/code/core/Mage/Checkout/Model/Type/Onepage.php(815): Mage_Sales_Model_Service_Quote->submitAll()
#12 /var/www/html/domain/public_html/app/code/core/Mage/Checkout/controllers/OnepageController.php(578): Mage_Checkout_Model_Type_Onepage->saveOrder()
#13 /var/www/html/domain/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#14 /var/www/html/domain/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#15 /var/www/html/domain/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /var/www/html/domain/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 /var/www/html/domain/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#18 /var/www/html/domain/public_html/index.php(83): Mage::run('ovh_nl', 'store')
#19 {main}
2016-12-10T16:59:34+00:00 ERR (3): 
Adyen_Payment_Exception: Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details in /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Exception.php:42
Stack trace:
#0 /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php(253): Adyen_Payment_Exception::throwException('Missing the enc...')
#1 /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(359): Adyen_Payment_Model_Adyen_Data_PaymentRequest->create(Object(Mage_Sales_Model_Order_Payment), 188.77, 'cc', 'domainofHolland...', 'ONECLICK', 'RECURRING', 0)
#2 /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(267): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Mage_Sales_Model_Order_Payment), 188.77, 'authorise')
#3 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order/Payment.php(1089): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Mage_Sales_Model_Order_Payment), 188.77)
#4 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 188.77)
#5 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#6 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#7 /var/www/html/domain/public_html/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): Mage_Sales_Model_Order->place()
#8 /var/www/html/domain/public_html/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#9 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#10 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#11 /var/www/html/domain/public_html/app/code/core/Mage/Checkout/Model/Type/Onepage.php(815): Mage_Sales_Model_Service_Quote->submitAll()
#12 /var/www/html/domain/public_html/app/code/core/Mage/Checkout/controllers/OnepageController.php(578): Mage_Checkout_Model_Type_Onepage->saveOrder()
#13 /var/www/html/domain/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#14 /var/www/html/domain/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#15 /var/www/html/domain/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /var/www/html/domain/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 /var/www/html/domain/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#18 /var/www/html/domain/public_html/index.php(83): Mage::run('ovh_nl', 'store')
#19 {main}
2016-12-10T17:00:13+00:00 ERR (3): 
Adyen_Payment_Exception: Missing the encrypted data value. Make sure the Client Side Encryption(CSE) script did encrypt the Credit Card details in /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Exception.php:42
Stack trace:
#0 /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php(253): Adyen_Payment_Exception::throwException('Missing the enc...')
#1 /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(359): Adyen_Payment_Model_Adyen_Data_PaymentRequest->create(Object(Mage_Sales_Model_Order_Payment), 188.77, 'cc', 'domainofHolland...', 'ONECLICK', 'RECURRING', 0)
#2 /var/www/html/domain/public_html/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php(267): Adyen_Payment_Model_Adyen_Abstract->_processRequest(Object(Mage_Sales_Model_Order_Payment), 188.77, 'authorise')
#3 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order/Payment.php(1089): Adyen_Payment_Model_Adyen_Abstract->authorize(Object(Mage_Sales_Model_Order_Payment), 188.77)
#4 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 188.77)
#5 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#6 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#7 /var/www/html/domain/public_html/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): Mage_Sales_Model_Order->place()
#8 /var/www/html/domain/public_html/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#9 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#10 /var/www/html/domain/public_html/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#11 /var/www/html/domain/public_html/app/code/core/Mage/Checkout/Model/Type/Onepage.php(815): Mage_Sales_Model_Service_Quote->submitAll()
#12 /var/www/html/domain/public_html/app/code/core/Mage/Checkout/controllers/OnepageController.php(578): Mage_Checkout_Model_Type_Onepage->saveOrder()
#13 /var/www/html/domain/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#14 /var/www/html/domain/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#15 /var/www/html/domain/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /var/www/html/domain/public_html/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 /var/www/html/domain/public_html/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#18 /var/www/html/domain/public_html/index.php(83): Mage::run('ovh_nl', 'store')
#19 {main}

**Comment by rikterbeek** [comment]
Hi @seansan,

Please check the browser data that is logged as well and check if your checkout page has javascript error on that browser. Are you sure you are not overwritten our template page.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
yes we are sure

it only happens 1 in 100 cases .. but if you have many cases

also I see more reports about this ... apparently it does happen ...

**Comment by rikterbeek** [comment]
Please upgrade to latest version and let us know if this error still occurs on this version in a new issue.

Regards,
