### ISSUE TITLE
No iDeal payment options (Banks) when used in combination with OneStepCheckout extension

### ISSUE THREAD

**Issue by PixelGarden** [Adyen/adyen-magento#717]
Just upgraded to Adyen Payment 2.8.0.1 and notice that the Checkout Page when used in combination with OneStepCheckout (v.4.5.5) isn't displaying the iDeal bank options. The iDeal option can be selected but the selectbox isn't populated with any banks.

Previous version we used (v2.6.2) worked fine. 

Magento version is 1.9.2 and Adyen Subscription is also installed.

**Comment by rikterbeek** [comment]
Hi @PixelGarden,

It could be a configuration issue, could you check if you see multiple payments options in your checkout or only Ideal?  Could you check country germany do you see Sofort ? If this is not the case it looks like your skin or HMAC key is incorrect.

Regards,
Rik
Adyen

**Comment by PixelGarden** [comment]
Hi @rikterbeek,

Thanks for getting back to me.

We have multiple payment options: CreditCard, iDeal and previously also PayPal.

Not really sure why skin or HMAC key would need to be changed if I would upgrade the Adyen Magento extension from 2.6.2 to 2.8.0.1. It worked fine with 2.6.2.

If I access the checkout page without OneStepCheckout the bank options are available, so it seems a conflict arose after the upgrade to 2.8.0.1.

I can supply some URLs so you can see the issue for yourself. Please let me know if that would help.

**Comment by rikterbeek** [comment]
Hi @PixelGarden,

Did you solve your issues ? 2.8.0.1 is not a valid release 2.8.1 is.

Regards,
Adyen

**Comment by PixelGarden** [comment]
No, the problem still exists.

When I check the config.xml of the Payment Extension it says

`    <modules>
        <Adyen_Payment>
            <version>2.8.0.1</version>
        </Adyen_Payment>
    </modules> `

**Comment by rikterbeek** [comment]
Hi @PixelGarden,

Looks like you are not on a stable version please switch to a stable version you can download it here: https://github.com/Adyen/adyen-magento/releases

Regards,
Rik
Adyen

**Comment by PixelGarden** [comment]
Hi @rikterbeek 

With the latest versions of both Adyen Payment + Adyen Subscriptions the problem still remains. 

No bank options are displayed when selecting iDeal as payment option in combination with the OneStepCheckout extension. 

Developer of OneStepCheckout looked at the problem and but says the problem is related to the Adyen integration so he is unable to help me. 

Not sure what can be done to fix this. In older versions of the Adyen Payment modules it all worked fine, so something changed between updates which broke the functionality.

**Comment by rikterbeek** [comment]
Hi,

Let me know if this is still an issue It should be solved in latest versions of our extension.

Regards,
Rik
Adyen
