### ISSUE TITLE
Payment fee tax not applied

### ISSUE THREAD

**Issue by sandermangel** [Adyen/adyen-magento#718]
I've set up VAT for the Adyen payment fee but the tax seems to not be applied.
The order fields `payment_fee_amount` and `base_payment_fee_amount` are filled with the correct amount but the text fields stay empty. This way the taxcalculation is incorrect.

Dit some digging but couldn't figure out what went wrong

- Adyen/Payment v2.8.0

**Comment by rikterbeek** [comment]
Hi @sandermangel,

Are you using a static payment fee or a percentage ? With percentage there is no tax calculated there is a PR that have this but that needs to be merged into the fee module. For static fee it should be applied.

Regards,
Rik
Adyen

**Comment by sandermangel** [comment]
Hey Rik,

it's the static fee unfortunately. Not sure how to explain for you to reproduce.
I can't find any conflicts with other modules or anything like that.

**Comment by sandermangel** [comment]
Hi Rik, I hope you can take a look at this PR: https://github.com/Adyen/adyen-magento/pull/722
It fixed the issue for us. For specific details on our tax settings etc please send me a DM if required

**Comment by sandermangel** [comment]
Also for installment and fee percentage there doesn't appear to be a tax column in the DB. Not that I need them but I would like to make a complete PR

**Comment by rikterbeek** [comment]
Hi @sandermangel,

Thanks for your PR not have seen an issue with this before looks like the Tax total is not triggerd in your case. Could you send me your configuration through a DM ? I will comment into your PR so you can see what I mean.

Concerning adding tax to the fee percentage there is a PR #608 that has this it only needs to be added into the Fee module instead of a stand-alone fee module as done in the PR. 

Regards,
Rik
Adyen

**Comment by sandermangel** [comment]
@rikterbeek sent via slack :) regarding the PR that is outstanding. Can this in some way be merged any time soon?

**Comment by sandermangel** [comment]
@rikterbeek any progress on this? Right now we have to manually correct the tax reports for this bug

**Comment by sandermangel** [comment]
@rikterbeek any update on this?

**Comment by rikterbeek** [comment]
@sandermangel closing this issue as this is very old. Feel free to open a new issue if there are still issues we need to resolve.

Regards,
Rik
Adyen
