### ISSUE TITLE
Error in configuration path in Cc.php

### ISSUE THREAD

**Issue by franzludilabel** [Adyen/adyen-magento#731]
Hi,
I notified you by email the 22/09/2016 that there is an error in the following file : 
https://github.com/Adyen/adyen-magento/blob/develop/app/code/community/Adyen/Payment/Model/Adyen/Cc.php

It seems you still didnt fix it...

The configuration path is false. Instead of payment/adyen_hpp/disable_zero_total, it should be payment/adyen_cc/disable_zero_total
and instead of payment/adyen_hpp/disable_zero_total, it should be payment/adyen_cc/disable_zero_total.

Hope you will fix it soon, dont want to miss modifications in this file because I had to hard-override it.

**Comment by shanelja** [comment]
It looks like the code for this class was copied wholesale from `https://github.com/Adyen/adyen-magento/blob/develop/app/code/community/Adyen/Payment/Model/Adyen/Hpp.php`, you're completely right, lines 224 and 226 need changing from:

```
223       if (!is_null($quote)) {
224            $disableZeroTotal = Mage::getStoreConfig('payment/adyen_hpp/disable_zero_total', $quote->getStoreId());
225        } else {
226            $disableZeroTotal = Mage::getStoreConfig('payment/adyen_hpp/disable_zero_total');
227        }
```

to:

```
223       if (!is_null($quote)) {
224            $disableZeroTotal = Mage::getStoreConfig('payment/adyen_cc/disable_zero_total', $quote->getStoreId());
225        } else {
226            $disableZeroTotal = Mage::getStoreConfig('payment/adyen_cc/disable_zero_total');
227        }
```

This is trivial, I'll go and create a PR for this now. Thanks for raising an issue. 👍

**Comment by shanelja** [comment]
Thanks again, @franzludilabel, a pull request has been raised to remedy this, once @rikterbeek or another Ayden organisation member approves it, we'll be able to package up a release for you.

**Comment by rikterbeek** [comment]
Hi @shanelja,

This PR is accepted closing this issue now.

Regards,
Rik
Adyen
