### ISSUE TITLE
Adyen_Payment_Model_Adyen_Hpp missing parameter

### ISSUE THREAD

**Issue by leonhelmus** [Adyen/adyen-magento#736]
I think on line 261 of class Adyen_Payment_Model_Adyen_Hpp, the param is missing.
this is it now:
$isAvailable = parent::isAvailable();
but i think it has to be:
$isAvailable = parent::isAvailable($quote);
Otherwise i cant use the dispatch event for hpp methods.

**Comment by rikterbeek** [comment]
Hi @leonhelmus,

Thanks for letting us know. Would you able to change it yourself and do a Pull Request to our develop branch ? Then I will merge your fix into the code.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @leonhelmus,

This is now added see above fix.

Regards,
Rik
Adyen
