### ISSUE TITLE
IWD_Opc 6.0.0 does not work with the Adyen payment method

### ISSUE THREAD

**Issue by mozgbrasil** [Adyen/adyen-magento#737]
Hello

Good afternoon

I installed the module IWD_Opc 6.0.0 which is the version available today, 01/27/2017, but does not display the payment methods of Adyen

The IWD_Opc 4.6.3 module that comes with the previous version works with Adyen's payment methods!

https://www.iwdagency.com/extensions/one-step-page-checkout.html

https://github.com/Adyen/adyen-magento

![captura de tela de 2017-01-27 16-37-00](https://cloud.githubusercontent.com/assets/17202780/22383973/6c4f0654-e4b3-11e6-9736-04022a7dd9c1.png)
![captura de tela de 2017-01-27 16-37-04](https://cloud.githubusercontent.com/assets/17202780/22383976/6c5ccb40-e4b3-11e6-834e-24a4f9b58b45.png)
![captura de tela de 2017-01-27 16-37-25](https://cloud.githubusercontent.com/assets/17202780/22383975/6c558812-e4b3-11e6-8190-3a6fb9f7f06c.png)
![captura de tela de 2017-01-27 16-37-36](https://cloud.githubusercontent.com/assets/17202780/22383977/6c5f92ee-e4b3-11e6-8495-faf46b498f65.png)
![captura de tela de 2017-01-27 16-38-01](https://cloud.githubusercontent.com/assets/17202780/22383974/6c53ce8c-e4b3-11e6-87b0-d279ca6850fd.png)

**Comment by rikterbeek** [comment]
Hi @mozgbrasil,

If you only change the IWD checkout module then you know the problem lies there. Please contact them and asked what they have changed and why it is not showing the adyen payment methods any more.

Regards,
Rik
Adyen

**Comment by diedburn** [comment]
@mozgbrasil did you find a sollution for this issue?

**Comment by mozgbrasil** [comment]
Good Morning

I did not find the solution to this question

I no longer have access to IWD modules

As recommended it is always to use the updated versions of the software due to improvements and patches

I recommend testing using the new version of the IWD module, they may have corrected this issue
