### ISSUE TITLE
Support autocomplete for credit cards on mobile

### ISSUE THREAD

**Issue by siggi-hs** [Adyen/adyen-magento#742]
I would like to suggest adding autocomplete attributes to the credit card fields so mobile users can fill out their credit card information using the camera.

```autocomplete="cc-name"
autocomplete="cc-number"
autocomplete="cc-exp-month"
autocomplete="cc-exp-year"
autocomplete="cc-csc"```

**Comment by shanelja** [comment]
Hi, @siggi-hs, there is a similar discussion open on the following pull request: https://github.com/Adyen/adyen-magento/pull/740

**Comment by siggi-hs** [comment]
@shanelja Ah! great, thanks. Let's just close this issue then and i'll keep track on the other one.
