### ISSUE TITLE
Adyen test Account - Payment Review

### ISSUE THREAD

**Issue by nozuna** [Adyen/adyen-magento#744]
Adyen,

We are using a test account and are running into orders going into Payment Review.  Can you provide the steps to approve these orders?  Also, how can we configure to approve all orders in test mode?

Thanks,

Nick

**Comment by nozuna** [comment]
I checked the configuration settings in Magento and they are all set to Pending/Processing.

**Comment by rikterbeek** [comment]
Hi @nozuna,

Did you enable the notifications and setup your cronjob. If you need any more help with configuration please read the full manual here: https://docs.adyen.com/developers/magento this should explain everything. If you still have questions please contact as at magento@adyen.com.

Regards,
Rik
Adyen
