### ISSUE TITLE
status and state not correct on new order with HPP

### ISSUE THREAD

**Issue by ebaschiera** [Adyen/adyen-magento#746]
Hi,
I noticed that when using HPP, a new order is initializated in "payment_review" state and status based on bakend configuration (see https://github.com/Adyen/adyen-magento/blob/develop/app/code/community/Adyen/Payment/Model/Adyen/Hpp.php#L232 ). The statuses available in that configuration are loaded by adminhtml/system_config_source_order_status_new model (see https://github.com/Adyen/adyen-magento/blob/develop/app/code/community/Adyen/Payment/etc/system.xml#L212 ).
I think that this is an error, because this leads to a combination of state and status that are not related each other. The status will not belong to pending_payment.
What would be the correct way of fixing? Setting the state as "new" or setting the status as "pending_payment" (or, better, the default status for "pending_payment state)?

Thanks!
-Ermanno

**Comment by rikterbeek** [comment]
hi @ebaschiera,

We can make this generic we have just done that for the specific authorization status see:
https://github.com/Adyen/adyen-magento/commit/cdcac22160eb1d68c82ed414f9b20d0eb26fa505

Regards,

**Comment by rikterbeek** [comment]
Hi @ebaschiera,

This should be fixed with latest releases. Feel free to open a new issue if there is still a problem.

Regards,
Rik
Adyen
