### ISSUE TITLE
Adyen sending duplicate notification events on authorisation, causing customers to be charged twice

### ISSUE THREAD

**Issue by shanelja** [Adyen/adyen-magento#748]
Adyen version: 2.8.1
Mage version: 1.14.3.1
Adyen overloads: None

Hey guys, we are receiving duplicate `AUTHORISATION` notification events from `smartpay` payments. When this happens, duplicate entries are made to the `adyen_event_data_queue` table, instead of being picked up by `Adyen_Payment_Model_ProcessNotification::_isDuplicate`. I believe this is because the `_isDuplicate` method only checks for duplicate entries to the `adyen_event_data` table.

Fixing this method to make the `adyen_event_data_queue` table deduplicate breaks the `Adyen_Payment_Model_ProcessNotification::_updateNotProcessedNotifications` method, however, as it checks for duplicates before updating the order details, so if a queue item exists it will always fail to update.

An example from our `adyen_process_notification.log ` file showing the duplication of AUTHORISATION events is as follows (has been redacted to protect private information and slightly refactored to make it easier to read):

```
2017-03-03T10:29:01+00:00 DEBUG (7): Array
(   [processResponse begin] => Begin to process Notification
    [response] => Array(
            [originalReference] => 
            [reason] => 052979:6418:09/2017
            [merchantAccountCode] => 000111
            [eventCode] => AUTHORISATION
            [operations] => CANCEL,CAPTURE,REFUND
            [success] => true
            [paymentMethod] => mc
            [currency] => GBP
            [pspReference] => 000001
            [merchantReference] => 111111
            [value] => 2541
            [live] => true
            [eventDate] => 2017-03-03T10:29:00.29Z
            [amount] => Array([value] => 2541, [currency] => GBP))
    [info] => Add this notification with Order increment_id to queue: 111111
    [AddNotificationToQueue Step1] => Going to add notification to queue
    [AddNotificationToQueue Step2] => Notification is added to the queue)

2017-03-03T10:29:13+00:00 DEBUG (7): Array
(   [processResponse begin] => Begin to process Notification
    [response] => Array(
            [originalReference] => 
            [reason] => 052979:6418:09/2017
            [merchantAccountCode] => 000111
            [eventCode] => AUTHORISATION
            [operations] => CANCEL,CAPTURE,REFUND
            [success] => true
            [paymentMethod] => mc
            [currency] => GBP
            [pspReference] => 000001
            [merchantReference] => 111111
            [value] => 2541
            [live] => true
            [eventDate] => 2017-03-03T10:29:08.75Z
            [amount] => Array([value] => 2541, [currency] => GBP) )
    [info] => Add this notification with Order increment_id to queue: 111111
    [AddNotificationToQueue Step1] => Going to add notification to queue
    [AddNotificationToQueue Step2] => Notification is added to the queue)
```

As you can see, these are individual events triggered by `Adyen_Payment_Model_ProcessNotification::processResponse`, as such, these events are being sent by the Smartpay/Adyen servers.

**Comment by rikterbeek** [comment]
Hi @shanelja,

Saving the notification twice in the adyen_event_data_queue does not mean that it is executing twice. The processing of the notification is done by a cronjob processor. This process check as well if the notification is already processed. So your example of the notification will only be processed once. See https://github.com/Adyen/adyen-magento/blob/develop/app/code/community/Adyen/Payment/Model/ProcessNotification.php#L1549

Regards,
Rik
Adyen
