### ISSUE TITLE
error verifying merchangsin in Authenticate.php, when SSL requests

### ISSUE THREAD

**Issue by lortizcompegps** [Adyen/adyen-magento#749]
We change setup of our magento to only receive SSL request (frontend and back), so we have to setup adyen to reply to SSL to our site.
Then we have an exception here
We had to add urldecode here, because False auth is returned, and an exception is thrown with this message 'ResultUrl authentification failure'

        if (strcmp($localStringToHash, $response->getData('merchantSig')) === 0) {
            return true;
        }

to:

        if (strcmp($localStringToHash, urldecode($response->getData('merchantSig')) ) === 0) {
            return true;
        }

it seems that in success request merchantSig is not urldecoded or not well sent.

Do you know about this issue?
Do you know if is an apache setup or something like that?

Thank you

**Comment by rikterbeek** [comment]
Hi @lortizcompegps,

This part is checking if the signature is correct so there are no params manually changed. In the url there should be a merchantSig parameter. Make sure your result url is HTTPS and you do not have any redirects in your webserver configured.

Regards,
Rik
Adyen

**Comment by lortizcompegps** [comment]
We check in logs, the request from adyen for this parameter  in SSL are urlencoded.
I don't know if this issue only happend to us.

**Comment by rikterbeek** [comment]
Hi @lortizcompegps,

I think you are on a older plugin becasue you need to urldecode all parameters and this should be done like this:  https://github.com/Adyen/adyen-magento/blob/develop/app/code/community/Adyen/Payment/Model/Authenticate.php#L61-L86

Regards,
Rik
Adyen

**Comment by lortizcompegps** [comment]
Yes we have last version of ADYEN module version 2.8.1
but the problem is not here, is produced from adyen tpv page or after.
variable request has our merchanSig urlencoded, with our setup in SSL.

We will check this in another staging environment with another apache and linux version, and we will check if we reproduce same problem.

Thank you

**Comment by rikterbeek** [comment]
Hi @lortizcompegps,

Do that and if we need to make a code change let us know.

Regards,
Rik
Adyen

**Comment by lortizcompegps** [comment]
Finally i could check with an environment more like our production, and this change is not necessary.

Thank you
