### ISSUE TITLE
Elo credit card is detected as maestro

### ISSUE THREAD

**Issue by sabrinabandaree** [Adyen/adyen-magento#751]
Hello good afternoon

See according to pictures that is not working the use of ELO card

When searching the internet for "credit card test link"

We find numbers like

6362970000457013
5067268650517446

I found the following questioning that mentions a similar occurrence

Https://github.com/Adyen/adyen-cse-web/issues/7

![captura de tela de 2017-03-17 16-56-33](https://cloud.githubusercontent.com/assets/26491932/24060593/be0da81a-0b32-11e7-9e11-01f9f809a6a3.png)

**Comment by sabrinabandaree** [comment]
Hello good Morning

In contact with Cielo I just received the updated BINS list for the ELO card

![image001](https://cloud.githubusercontent.com/assets/26491932/24101443/1ca5f564-0d57-11e7-9ac1-04c37616421e.jpg)

**Comment by rikterbeek** [comment]
Hi @sabrinabandaree,

They will be processed as ELO only in the front-end because it has the same started bin ranges as Maestro indicated as Maestro we will have a look how we can show this correctly in the front-end.

Regards,
Rik
Adyen
