### ISSUE TITLE
feature request: small refund

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#752]
Hi we sometimes have customers where a discount code did not work. Or they bargain a small discount (afterwards ....) 

Now 
- we create a credit memo
- set no returns
- small adjustment

Question is: 
- would it be an idea for a "quick refund" or "quikc adjustment" field where there is we dont go thr the whole credit memo process

Just an idea.

**Comment by rikterbeek** [comment]
Hi @seansan,

Looks like a customization that is needed specific for your needs. This looks like a customization that is not related to our payments extension. What you can do is just build in logic into this field to create a online partial creditmemo. Magento will understand what payment method is related to this and will do a online partial capture to the payment provider that is used. There are many system integrators that can build this for you.

Regards,
Rik
Adyen
