### ISSUE TITLE
Boleto payment not sending new order email

### ISSUE THREAD

**Issue by fernandoperigolo** [Adyen/adyen-magento#753]
Hi, Guys.

Are anyone using Boleto payment? Can you tell if new order emails is been sent? I dont know if it is a module problem or it is about my store.

Thank you all

**Comment by rikterbeek** [comment]
Hi @fernandoperigolo,

Are you using the Adyen Boleto payment methode ? Then the order confirmation mail is send when the order is created.

Regards,
Rik
Adyen

**Comment by fernandoperigolo** [comment]
Thanks, i will double check module instalation. It is not working here.
