### ISSUE TITLE
Adyen chargeback does not void the transaction

### ISSUE THREAD

**Issue by sandermangel** [Adyen/adyen-magento#754]
It happens quite frequently a transaction is chargebacked after a few seconds, see: http://i.imgur.com/JxmHI3d.png
But by then the order already has a paid invoice after having gotten the notification it was captured
and the invoice is not voided.
Basically it's not possible to determine if the invoice was paid or not.
I would expect the total due amount to be the order amount after a chargeback #

**Comment by rikterbeek** [comment]
HI @sandermangel,

Because of the invoice already created the total due is zero.  Based on the CAPTURE notification you know if the payment was successfully paid.

Regards,
Rik
Adyen

**Comment by sandermangel** [comment]
Thanks for the answer, am I right to assume that any order with `adyen_event_code` "CAPTURE : TRUE" is successfully captured?
That would be a safe condition to forward to fulfillment?

**Comment by rikterbeek** [comment]
Hi @sandermangel,

Yes indeed this is triggered by the notification and provide you the right information to sip the goods.

Regards,
Rik
Adyen
