### ISSUE TITLE
Not urgent. But FYI: Undefined index: HTTP_USER_AGENT

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#778]
Sometimes in logging

Notice: Undefined index: HTTP_USER_AGENT  in app/code/community/Adyen/Payment/Model/Adyen/Hpp.php on line 161

**Comment by rikterbeek** [comment]
Hi @seansan,

HTTP_USER_AGENT is a PHP variable with server data please make sure this has a value!
http://php.net/manual/en/reserved.variables.server.php

Regards,
Rik
Adyen
