### ISSUE TITLE
Order update emails not being sent in version 2.9.0

### ISSUE THREAD

**Issue by hughconway** [Adyen/adyen-magento#785]
Order update emails including refund notifications do not appear to be sent to the customer, only to the admin copy email address.  I have "Customers receive order status update email (deprecated)." set to "No" as instructed by Adyen helpdesk.

**Comment by rikterbeek** [comment]
Hi @hughconway,

What do you want to achieve ?

Regards,
Rik
Adyen

**Comment by hughconway** [comment]
I would like customers to recieve updates when I manually change the status of an order but not when it is an automatic system change such as moving from 'payment review' to 'processing'.

**Comment by rikterbeek** [comment]
Hi @hughconway,

I think if you create a manual comment history you can define if it will send out an mail to the customer. I don't think this has anything todo with our payments module.

Regards,
Rik
Adyen
