### ISSUE TITLE
Is it possible to add a status to these steps below?

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#794]
Is it possible to add a status to these steps below?

Mainly AUTHORISED; we would like to set a status pending_payment or something else

1. New order, no payment
2. New order payment authorized
3. New order payment authorisation, goes to processing state 

Dilemma is that some payments linger a little longer than expected between 1 and 3 .... and there is no status to capture this "phase" ... can we add a status setting in backend for this? (so we can identify these also --- )

Also what is the "real" difference between AUTHORISED and AUTHORISATION?

![image](https://user-images.githubusercontent.com/652395/27220034-faff0c12-5283-11e7-991e-764b5cc973c9.png)

**Comment by rikterbeek** [comment]
Hi @seansan,

If you see the line above there is explained the differents. So authorised is coming from the resultUrl and the AUTHORISATION is coming from the notifications. Only on the notification AUTHORISATION we change the status because resultUrl is less secure because of man in the middle attacks. If the order is created it will have a pending status and when it has an authorisation it will move to the status you have selected.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
Aha!

The dilemma is that authorized by resultUrl payments are sometimes
authorized later than expected; this leeds to abandoned cart stuffs. So if
we could assign the resultUrl payments we at least capture part and can
exclude them (because they were paid)

Hope it is clear

Possible quick win

**Comment by rikterbeek** [comment]
Hi @seansan,

The resultUrl does nothing and updates nothing so I don't see that this can lead to abandoned card stuff ? The server to server communication only provides the correct result on the payment and only on this result you should do actions. This is already build into the extension so don't see any customizations needed.

Regards,
Rik

**Comment by seansan** [comment]
correct now it does nothing
it updates the history (why does it do that?)
it is information: so why not create a status updated (call it authorized)
at least then we know that the payment was accepted (only waiting for cron
for double confirm)

**Comment by rikterbeek** [comment]
Hi @seansan,

It is just extra information to know if a customer came back to the store. Updating the status could cause serious issues with the notification processing. It could be that the notification process and result are executed at the same time in this case if both processes are saving a status it could lead to unexpected behaviour and a wrong status as result. We had this in older versions so we have removed the status update on the resultUrl this solves the issue.

Regards,
Rik
Adyen
