### ISSUE TITLE
AES key generation, sjcl.random.randomWords, why paranoia is set to 0 ?

### ISSUE THREAD

**Issue by Mayfly277** [Adyen/adyen-magento#797]
Hi,
i see you use the function sjcl.random.randomWords for the AES kay generation with the paranoia parameter set to 0

As you can see in this issue : https://github.com/bitwiseshiftleft/sjcl/issues/77
The author of the js lib say : 
>  If, on the other hand, your clients are passing paranoia=0 to anything for reasons other than testing, please tell them not to do that

So i am concerned about the usage of this paranoia with the 0 value. Does it means a weak security on the AES encryption of the module?

* Code concerned :
```js
    AESKey.prototype = {

        constructor : AESKey,

        key : sjcl.random.randomWords( 8, 0 ),

        encrypt : function ( text ) {

            return this.encryptWithIv( text, sjcl.random.randomWords( 3, 0 ) );

        },
```

regards.

**Comment by rikterbeek** [comment]
Hi @Mayfly277,

Thanks for addressing this issue. Our magento extension is using our Javascript Library that has it's own repository here: https://github.com/Adyen/adyen-cse-web can you please create an issue there then my colleagues who are responsible for this part can pick it up.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @Mayfly277,

Did you raise the question there ?
I am closing this issue now.

Regards,
Rik
Adyen

**Comment by Mayfly277** [comment]
Hi @rikterbeek,
for your information, this was fixed by adyen cse-web in the release 0_1_20 
(see commit : https://github.com/Adyen/adyen-cse-web/commit/7282748da8aa90f93d4b6419a92404b71c9f6adb)

comment was : 
> Improve entropy setup for older browsers

Regards.
