### ISSUE TITLE
E_ERROR: Call to a member function getAdditionalInformation() on boolean

### ISSUE THREAD

**Issue by Jitheesh** [Adyen/adyen-magento#798]
Magento EE 1.14.2.1
Adyen: 2.8.1

Stack trace
E_ERROR: Call to a member function getAdditionalInformation() on boolean
in Adyen_Payment_ProcessController::validate3dAction 
called at /app/code/community/Adyen/Payment/controllers/ProcessController.php (184) 

in Adyen_Payment_ProcessController::validate3dAction called at /app/code/core/Mage/Core/Controller/Varien/Action.php (418) 

in Mage_Core_Controller_Varien_Action::dispatch called at /app/code/core/Mage/Core/Controller/Varien/Router/Standard.php (254) 

in Mage_Core_Controller_Varien_Router_Standard::match called at /app/code/core/Mage/Core/Controller/Varien/Front.php (172) in Mage_Core_Controller_Varien_Front::dispatch called at /app/code/core/Mage/Core/Model/App.php (365) 

in Mage_Core_Model_App::run called at /app/Mage.php (692) 

in Mage::run called at /index.php (111)

Reason for this issue:
`           $payment = $order->getPayment();

            $paRequest = $payment->getAdditionalInformation('paRequest');

            $md = $payment->getAdditionalInformation('md');

            $issuerUrl = $payment->getAdditionalInformation('issuerUrl');

            $infoAvailable = $payment && !empty($paRequest) && !empty($md) && !empty($issuerUrl);

            // check adyen status and check if all information is available

            if (!empty($adyenStatus) && $adyenStatus == 'RedirectShopper' && $infoAvailable)`
If payment object is missing on order then it will ends with above error.

**Comment by rikterbeek** [comment]
Hi @Jitheesh,

Does the $order is an existing order object ? Order should have the method getPayment() method or did you extend the order object ?

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @Jitheesh,

Is this still an issue if so can you respond to my last question ? If not I am closing this issue.

Regards,
Rik
Adyen

**Comment by Jitheesh** [comment]
HI @rikterbeek 

Yes $order is an existing order object, We didn't extended  Mage_Sales_Model_Order class.

As far as I can see _$payment = $order->getPayment();_ is returning false. 
`    /**
     * Retrieve order payment model object
     *
     * @return Mage_Sales_Model_Order_Payment
     */
    public function getPayment()
    {
        foreach ($this->getPaymentsCollection() as $payment) {
            if (!$payment->isDeleted()) {
                return $payment;
            }
        }
        return false;
    }`

That's why this line, _ $paRequest = $payment->getAdditionalInformation('paRequest');_ ,is ends with error.

Also I can see you already added $payment object validation on this line of code
`$infoAvailable = $payment && !empty($paRequest) && !empty($md) && !empty($issuerUrl);`

If you can do the same on above lines, it would be more safe.

Thanks,
Jitheesh

**Comment by rikterbeek** [comment]
Hi @Jitheesh,

This is already solved in our latest extension see:
https://github.com/Adyen/adyen-magento/blob/develop/app/code/community/Adyen/Payment/controllers/ProcessController.php#L185-L187

Regards,
Rik
Adyen
