### ISSUE TITLE
Setting: Ignore refund notification also returning items to stock?

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#799]
When the setting "Ignore refund notification" is set to NO

The notifications are processed and credit memo's are created

Unexpected situation is: that is also returns all items to stock

We added some screenshots as example

Can we create an extra settings to defines "how" it is handled? Or make it so that the products (return) itself are managed in Magento and not via Adyen ... 
[FLOW.docx](https://github.com/Adyen/adyen-magento/files/1102688/FLOW.docx)

**Comment by rikterbeek** [comment]
Hi @seansan,

If you want to do redunds from the backoffice but do not want the items back in stock set this setting to YES. If you want a credit memo then you can create a offline credit memo and define that you do not want the items back in stock.

Regards,
Rik
Adyen
