### ISSUE TITLE
Change #652 breaks Magento sessions functionality

### ISSUE THREAD

**Issue by welou** [Adyen/adyen-magento#801]
The change introduced regarding issue #652 (implemented in commit 0050e0611badb7dbf8fa4743740887c71018df62) breaks session functionality.

The addMethodsToConfig() - functions attempt to use the sessions, but at the time of the "adminhtml_controller_action_predispatch_start" - event they are not yet initialised.

Manipulating the sessions this early prevents the creation of adminhtml cookie, which in turn leads to other issues. Admin user is still able to browse the admin area, but different functionalities that attempt to evaluate the admin session will fail.

In place of "adminhtml_controller_action_predispatch_start" the event "controller_action_predispatch_adminhtml" could be used instead. Additionally if this event is only needed on the admin side it could be declared within the "adminhtml" node instead of "global".

Related information from Alan Storm regarding session usage: http://alanstorm.com/magento_sessions_early/

In the "Consequences" chapter he goes into more detail on what type of issues might arise from using sessions before preDispatch() has been called.

Under the heading "Fixes" he states that especially the event "adminhtml_controller_action_predispatch_start" among a couple others should be avoided when it comes to manipulating sessions.

**Comment by rikterbeek** [comment]
Hi @welou,

Sorry for the late reply and thanks for your detailed description of the issue. I do not see many issues with switching to the controller_action_predispatch_adminhtml event. Indeed it can be moved to the adminhtml node. See change above does this solve all your issues ?

Regards,
Rik
Adyen

**Comment by welou** [comment]
Hi @rikterbeek, thanks for getting back regarding this. That change looks good to me. In fact we already applied that change on the live site where we encountered this issue and have observed no problems during the past weeks.

**Comment by rikterbeek** [comment]
Hi @welou,

Great!

Regards,
Rik
Adyen
