### ISSUE TITLE
Would it be possible to show some "certainty" info in Magento for CC's?

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#804]
Would it be possible to show some "certainty" info in Magento for CC's?

Like liability shift? 
Fraud score? 
If name & address matches yes or no

![image](https://user-images.githubusercontent.com/652395/28218464-e9e3e5c4-68b8-11e7-8f7e-d857548f283e.png)

**Comment by rikterbeek** [comment]
Hi @seansan,

AVS and fraudscore is already passed to magento. If you go into your server communication and select Additional Settings here you can turn it on. For more questions about the settings please contact us at support@adyen.com.

Regards,
Rik
Adyen
