### ISSUE TITLE
Add support for GoMage LightCheckout

### ISSUE THREAD

**Issue by hughconway** [Adyen/adyen-magento#805]
Hi there,

I don't know how to add new files to Github but here are the amended files needed to add support for the GoMage LightCheckout module:

/app/code/community/Adyen/Payment/etc/config.xml

/app/design/frontend/base/default/layout/adyen.xml

Can someone review and merge them please so that I can stop manually altering files on each new version of the module?

Thanks,

Hugh

[files.zip](https://github.com/Adyen/adyen-magento/files/1158803/files.zip)

**Comment by rikterbeek** [comment]
Hi @hughconway,

Could you provide me the changes that you did ? What do you mean with new files ?

Regards,
Rik
Adyen

**Comment by hughconway** [comment]
Hi Rik, 

I added: 

 <controller_action_predispatch_gomage_checkout>
 <observers>
 <adyen_payment_hpp>
 <class>adyen/observer</class>
 <method>addMethodsToConfig</method>
 </adyen_payment_hpp>
 <adyen_payment_billing_agreement>
 <class>adyen/billing_agreement_observer</class>
 <method>addMethodsToConfig</method>
 </adyen_payment_billing_agreement>
 </observers>
 </controller_action_predispatch_gomage_checkout> 

to /app/code/community/Adyen/Payment/etc/config.xml at Line 214 

and: 

 
 <gomage_checkout_onepage_index>
 <reference name="head">
 <action method="addJs"><script>adyen/payment/cc.js</script></action>
 <action method="addJs"><script>adyen/payment/iban.js</script></action>
 <action
method="addCss"><stylesheet>css/adyenstyle.css</stylesheet></action>
 </reference>
 <reference name="after_body_start">
 <block type="core/template" name="after_body_start_script"
template="adyen/after_body_start.phtml" />
 <block type="core/text" name="adyen.diners.validation" after="-">
 <action method="setText">
 <text>
 <![CDATA[<script type="text/javascript">
 Validation.creditCartTypes.set('MC',
[RegExp('(^5[1-5]|^2[2-7])[0-9]{14}$'), new RegExp('^[0-9]{3}$'),
true]);
 Validation.creditCartTypes.set('DC', [new
RegExp('^3(?:0[0-5]|[68][0-9])[0-9]{11}$'), new RegExp('^[0-9]{3}$'),
true]);
 Validation.creditCartTypes.set('CB', [new
RegExp('^4[0-9]{12}([0-9]{3})?$'), new RegExp('^[0-9]{3}$'), true]);
 Validation.creditCartTypes.set('ELO', [new
RegExp(/^((((636368)|(438935)|(504175)|(451416)|(636297)|(506699))d{0,10})|((5067)|(4576)|(4011))d{0,12})$/),
new RegExp('^[0-9]{3}$'), true]);
 Validation.creditCartTypes.set('hipercard', [new
RegExp(/^(606282d{10}(d{3})?)|(3841d{15})$/), new RegExp('^[0-9]{3}$'),
true]);
 </script>]]>
 </text>
 </action>
 </block>
 </reference>
 </gomage_checkout_onepage_index> 

to /app/design/frontend/base/default/layout/adyen.xml at line 142 

Thanks, 

Hugh 

On 2017-07-19 11:37, Rik ter Beek wrote: 

> Hi @hughconway [1], 
> 
> Could you provide me the changes that you did ? What do you mean with new files ? 
> 
> Regards,
> Rik
> Adyen 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/hughconway
[2]
https://github.com/Adyen/adyen-magento/issues/805#issuecomment-316344743
[3]

**Comment by rikterbeek** [comment]
Hi @hughconway,

It is added see commit above.

Regards,
Rik
Adyen
