### ISSUE TITLE
No billing agreement after checking the Remember these details checkbox from checkout

### ISSUE THREAD

**Issue by chester310590** [Adyen/adyen-magento#818]
This is the code, responsible for displaying the checkbox:

`<?php if($this->canCreateBillingAgreement()): ?>
    <li id="adyen-cc-remember-these-details" class="adyen_payment_input_fields">
        <div class="input-box">
            <div class="v-fix">
                <input type="checkbox" name="payment[store_cc]" id="<?php echo $_code ?>_store_cc" value="1" checked />
                <label for="<?php echo $_code ?>_store_cc"><em>*</em><?php echo $this->__('Remember these details') ?></label>
            </div>
        </div>
    </li>
    <script type="text/javascript">
        // don't show save cc for quest checkout. Only possible to detect with javascript
        if ($('login:guest') && $('login:guest').checked) {
            $('adyen-cc-remember-these-details').hide();
        }
    </script>
    <?php endif; ?>`

**Story to reproduce:** 

After choosing the `Credid Card` option from checkout , filled all of the inputs with one of the test account from [here](https://gist.github.com/j3j5/8b3e48ccad746b90a54a) and finished the order I would expect to have a Billing agreement in the billing agreement grid from adminpanel. This isn't happening :|

**Comment by rikterbeek** [comment]
Hi @chester310590,

Could be that you do not have the recurring_contract notification turn on. Could you let us know your merchant account please address this to magento@adyen.com so we can turn this on for you.

Regards,
Rik
Adyen
