### ISSUE TITLE
Possibility to use with PHP7?

### ISSUE THREAD

**Issue by BrotherMouzone** [Adyen/adyen-magento#821]
Hi,

Not sure if this is the right place to ask this so sorry if it's wrong. We are running a PHP7 install of Magento 1.9, but the installer of this module requires much older version "requires PHP version  >= 5.3.3 and <= 6.0.0". Is there any hope of the module being update to be PHP7 compatible in the near future? Has anyone tried to make it work with PHP7? (Forced install crashed our test site).

Thanks for any info on this matter.

**Comment by lancergr** [comment]
Hi @BrotherMouzone 

How did you install the plugin?
The proposed way is to follow these github instructions
https://docs.adyen.com/developers/plug-ins-and-partners/magento/magento-1#github

Regards,
Giorgos
Adyen

**Comment by lykhouzov** [comment]
Hi @BrotherMouzone .
locally i am running m1.14.3 EE on php7. with this module.
it was installed manually.
So, officially it could not be support by php7. but on practice it's working.
also, there is a phpcs module in order to find compatibility for specific verision of php, so you could use it and check if this module really could be supported by php7.

**Comment by rikterbeek** [comment]
Hi @lykhouzov, @BrotherMouzone 

The extension is possible to use probably on PHP7 most of the time there are issues with magento core system. We don't limit the version to 6.0.0 not sure where you get that from ?

Regards,
Rik
Adyen

**Comment by BrotherMouzone** [comment]
I tried downloading it through magento connect which gave the the original PHP version check error. After downloading the version from github and instlaling manually, at least it's not giving any error so I guess it's working alright.

**Comment by rikterbeek** [comment]
Hi @BrotherMouzone,

This is indeed defined in our xml of the extension for Magento Connect. Thanks for addressing this we will fix this in a later release on magento connect. Best to download all versions of our extension through our GitHub.

Regards,
Rik
Adyen
