### ISSUE TITLE
Quick Win: Abilito to set Status on: AUTHORISED (dont worry not state)

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#826]
Abilito to set Status on: AUTHORISED (dont worry not state)

I understand now works like AUTHORISATION  via batch/api then complete order

But we see more than 88% does go to the succes page -- and we have many processes after the order confirmation ... so knowing "sooner/direct" that the order is OK is very important

I understand youo dont want to confirm Payment because you want 100% certainty via batch/api

But can we do this
- ability in backend to assign our own Status (belonging to State New, not Processing)
- at least then we can distinguish between: complete not paid + high reeason to trust paid

Also in the screenshot below you can see AUTHORISED does not status update, whilst AUTHORISATION  does -- why not create a simple option to set own state for AUTHORISED too -- if this is important for merchants to have

Hoping you can add this quick win, big difference for us - and I imagine some others

![image](https://user-images.githubusercontent.com/652395/29941695-b448e382-8e93-11e7-9eb7-1831650c3b36.png)

**Comment by rikterbeek** [comment]
Hi @seansan,

This request you already did in #794. As I said back then this is not something we can do because this can result in unexpected behaviors becasue of multi-thread actions.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
we are not suggesting to set state
rather status only

and I dont see how unexpected behaviors can occur. The confirmation is
immediate + you can add an "has not been touched by confirmations" check
so if customers confirms immediate + not touched by confirmations api/batch
then set status
otherwise ignore because  confirmations api/batch is leading
