### ISSUE TITLE
?utm_nooverride=1 is part of success url as "folder structure" /utm_nooverride/1

### ISSUE THREAD

**Issue by kimitimonen** [Adyen/adyen-magento#827]
In /app/code/community/Adyen/Payment/controllers there are several lines as follows:

`$this->_redirect('checkout/onepage/success', ['utm_nooverride' => '1']);`

In order to get ?utm_nooverride=1 appended to success url as parameter, should above lines be:

`$this->_redirect('checkout/onepage/success', ['_query' => ['utm_nooverride' => '1']]); `

This seems to be fixed in your magento 2 extension but not in magento 1 extension:

https://github.com/Adyen/adyen-magento2/commit/7732ef9bc1a6fac94ef17c1eecfaec0b020fc620

In our google analytics we get hits to /checkout/onepage/success/utm_nooverride/1/ which i guess is not correct.

I guess this was the original problem: https://github.com/Adyen/adyen-magento/issues/475 There are other ways to do referral exclusion in google analytics these days --> this feature might be totally obsolete. @seansan @rikterbeek 

Thanks in advance and sorry if above problem is not really a problem but me being stupid :)

-Kimi-

**Comment by rikterbeek** [comment]
Hi @kimitimonen,

Looks indeed to the same error. Could you change this on your end validate if if this solves your issues ? if so would you be able to do a PR to our repository ?

Regards,
Rik
Adyen

**Comment by kimitimonen** [comment]
Hi @rikterbeek 

Did some test drives in our dev:
- The success url indeed is wrong but it works and the correct success page content is visible and you analytics is configured to run transactional tag on url CONTAINING /checkout/onepage/success/ but for some sites this might be a problem if they run transactional tag on url MATCHING /checkout/onepage/success/

- I need to test some more since i can't determine yet why the "wrong" success url "works"

![image](https://user-images.githubusercontent.com/20117176/30051691-a8328fee-922b-11e7-8798-2f22408a214d.png)

**Comment by kimitimonen** [comment]
Hi,

After more testing the "fix" in my first message, it works if you want to use the parameters correctly. We chose to remove parameters altogether since it is not optimal way to get rid of "payment referrals" in analytics.

Hope this helps 👍 

Kind regards

-Kimi-

**Comment by rikterbeek** [comment]
Hi @kimitimonen,

Great are you able to do a PR to the repo so it is updated there as well ?

Regards,
Rik
Adyen

**Comment by olivercastro** [comment]
Hi @rikterbeek 
When will it be included in the future releases?

**Comment by rikterbeek** [comment]
@seansan @kimitimonen,

The fix has been provided. I think we covered all our control urls with this prefix. If we are missing something please feel free to open a PR so we can add it into the code.

Regards,
Rik
Adyen

**Comment by henryvanderborg** [comment]
> @seansan @kimitimonen,
> 
> The fix has been provided. I think we covered all our control urls with this prefix. If we are missing something please feel free to open a PR so we can add it into the code.
> 
> Regards,
> Rik
> Adyen

- Can you please let me whether the fix has been provided in a release? 
I see similar issues, people arriving at checkout/onepage/success/utm_nooverride/1/. 
note: I don't see any mentioning of fixes after 2.9.0 https://github.com/Adyen/adyen-magento/releases/tag/2.9.0  We running a more recent version than 2.9.0. 

- Can we disable the functionality if this turns out not to be best practice for universal analytics? 
If someone has a link to pages explaining well why this is no longer best practice, please step in.
