### ISSUE TITLE
Order forced off of onhold 

### ISSUE THREAD

**Issue by sandermangel** [Adyen/adyen-magento#828]
A commit by D. Verkade is forcing onhold orders to go off of onhold.
Since onhold doesn't happen 'naturally' in Magento, it's a state explicitly given by an admin', this will cause unwanted or unexpected behavior.

For us it's currently a showstopper causing us not to deploy the new version. 
I would suggest wrapping it in a feature flag. would be happy to discuss it with @rikterbeek and @dverkade 
on slack or something.

https://github.com/Adyen/adyen-magento/commit/8859848f6aca565c9994725ac079f42ce2adf8e6

**Comment by rikterbeek** [comment]
Hi @sandermangel,

Thanks for letting us know. The order is parked but the order is actual paid for this can happen in some edge case scenario. Why don't you want to un-hold the order becasue then it remains on hold but the payment went through. We could move to slack if it becomes to complex but would you be able to answer some of my questions here ?

Regards,
Rik
Adyen

**Comment by sandermangel** [comment]
@rikterbeek as discussed the solution, I went ahead and made a PR https://github.com/Adyen/adyen-magento/pull/832

**Comment by rikterbeek** [comment]
Hi @sandermangel,

Thanks! this one is merged :)

Regards,
Rik
Adyen
