### ISSUE TITLE
Payment link from Magento sends customer to wrong store

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#829]
Payment link from Magento sends customer to wrong store

Magento store
With multiple store views (store A store.com = primary, store B myshop.com = secundary, store C etc)
Create sale for the non primary (adyen) store (actual store for this customer is = store B myshop.com)
Send payment link
Customer makes succesful payment
actual: Is directed to te primary store store.com success page

expected: Is directed to te actual store B myshop.com succes page

**Comment by rikterbeek** [comment]
Hi @seansan,

Could you please create a skin that does not have a resultUrl defined.
ResultUrl of magento does not make sense because magento is not able to show the success page because the order will be retrieved from the session.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
Thanks Rik

To be clear:
Is this a test?
Or the solution?

This field is currently set in our skin: should we leave it empty?

[image: Inline image 1]

**Comment by rikterbeek** [comment]
Hi @seansan,

This is the solution so please indeed keep it empty.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
it was set some years ago by adyen - fyi .. because maybe others have this
*old* setting then too

for now: we removed the resulturl, is now empty

**Comment by rikterbeek** [comment]
Hi @seansan,

Don't understand what you mean. Great that you removed it.

Regards,
Rik
Adyen
