### ISSUE TITLE
Option to add notitifications job in own job?

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#830]
Would it be good to add a shell file so admin can call notitifications processing in own job?

This way the adyen job can run at its own pace ( we can plan as we want and call the adyen shell file)

And Adyen notitifications does not wait/depend on other cron jobs (seeing as payment is so important)

Seems like a quick win to add a file that calls the right methods + check if not already running ... and processes queue ... (and if used: add option to config to turn default cron functionality off)

```
<?php

require_once 'abstract.php';
class Adyen_Shell_Notifications extends Mage_Shell_Abstract
{
    public function run()
    {
        error_reporting(E_ALL);
        ini_set('error_reporting', E_ALL);
        ini_set('max_execution_time', 360000);
        set_time_limit(360000);

    }

    /**
     * Retrieve Usage Help Message
     *
     */
    public function usageHelp()
    {
        return <<<USAGE
Usage:  php -f adyennotifications.php -- [options]
                      
                      Run (proces notitifications in own job)
  --help              Help

USAGE;
    }

}

$shell = new Adyen_Shell_Notifications();
$shell->run();


```

**Comment by rikterbeek** [comment]
Hi @seansan,

Better to work with cron groups so it is not stalled. In M1 this is not out of the box possible but the 	
Aoe_Scheduler is a good tool to use to solve this kind of problems see: https://github.com/AOEpeople/Aoe_Scheduler 

Regards,
Rik
Adyen

**Comment by seansan** [comment]
jep thanks we use this and know this - aoe is an external tool

however we made the suggestion of a separate shell caller within adyen - we
see this works very well with other critical jobs ... and it seems like a
quick win - all the methods already exist .. there are also some upsides:
like having the ability to monitor/report long runs, solve/report several
misses, etc

ps. i dont see how it could stall if you configure it like this

thanks!

**Comment by rikterbeek** [comment]
Hi @seansan,

I don't see why cronjobs is not an good approach because you have monitor and reporting over this.With AOE you can define different groups that need to run on a different time period. If you do this and define our cronjob in a unique group I do not see issues with other crons stalling our job.
Shell scripts you need to manually define in in your server cron while  cronjobs is a functionality where you don't need to do any customizations and is easier to use. If you want to go for a shell script that is fine but not something we will provide support on.

Regards,
Rik
Adyen

**Comment by seansan** [comment]
Posting for future users

`* * * * * flock -n ~/.adyen_notification_mage.lock /usr/local/bin/magerun --root-dir=/var/www/html/public_html/ sys:cron:run adyen_payment_process_notification_queue >> /var/www/html/public_html/var/log/adyen_notification_cron.log`

Just came from webstore group where multiple admins have adyen running in own thread

So here is a possible solution

But maybe offering a quicker way via shell would not even be such a bad idea - and then supported by default
