### ISSUE TITLE
wrong images on latest version for magento 1

### ISSUE THREAD

**Issue by kimitimonen** [Adyen/adyen-magento#836]
Hi, 

It seems that the latest version of the extension overrode payment methods images with wrong/old images.

**Examples**

Finnish e-banking should be Paytrail logo, not "suomen verkkomaksut" which does not even exist anymore:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/20117176/30486332-ddd4424a-9a38-11e7-8b9c-4b4cddb7031e.png">

I think this is not correct logo for Sofort either:

<img width="261" alt="image" src="https://user-images.githubusercontent.com/20117176/30486358-f9412afc-9a38-11e7-8bdf-feb4e3864fdb.png">

Quite a urgent one since it is directly tied to conversion to have correct logos.

I apologise if i'm wrong and this is another case of "idiot Kimi".

-Kimi-

**Comment by Aleffio** [comment]
Hi Kimi,

We are working on a fix for this,

You can change the logos with the ones you can find here:
https://github.com/Adyen/adyen-payment-icons

ebanking_FI.png contains the Paytrail logo
directEbanking_de.png contains the Sofort logo,

Kind Regards,
Alessio

**Comment by Aleffio** [comment]
Hi @kimitimonen ,

The images have been replaced,

Kind Regards,
Alessio,
Adyen
