### ISSUE TITLE
Precision about the supported versions of Magento

### ISSUE THREAD

**Issue by xaviermarchegay** [Adyen/adyen-magento#838]
Hi,

I am working on an old Magento version (1.10EE) and I realized that the localstorage of my browser was never reset (not good security-wise).

https://github.com/Adyen/adyen-magento/blob/be88e18bb0d4ed1b93beff0a0dd93945fcb16836/js/adyen/adminhtml/sales.js#L19

Apparently, the trigger "dataLoaded" was introduced in the version [1.7.0.0CE](https://github.com/OpenMage/magento-mirror/blame/505e8e982ad5f4fd22005060564cad210aab7b6f/js/mage/adminhtml/sales.js#L119) (1.12EE).

I think it should be important to precise that the minimum requirements are Magento 1.7CE/1.12EE.

**Comment by rikterbeek** [comment]
Hi @xaviermarchegay,

The plugin support 1.8 and higher. This means enterprise 1.13 and higher. I strongly advise you to upgrade your magento version.

Regards,
Rik
Adyen

**Comment by xaviermarchegay** [comment]
I know that. However, it is not said anywhere in the README.

> This is the Adyen Payment plugin for Magento 1.x. The plugin supports the Magento Community and Enterprise edition.

should be changed to 
> This is the Adyen Payment plugin for Magento **1.8.x and higher**. The plugin supports the Magento Community and Enterprise edition.

**Comment by rikterbeek** [comment]
Hi @xaviermarchegay,

Agreed we will update our documentation and github readme.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
This is now added into our documentation and github.

Regards,
Rik
Adyen
