### ISSUE TITLE
Payment method setup is returned "Access denied." when you use permissions role resources custom

### ISSUE THREAD

**Issue by sabrinabandaree** [Adyen/adyen-magento#854]
**Magento version**: 1.9.3.6
**Plugin version**: 2.9.5
**Description**

Good Morning

Payment method setup is returned "Access denied." when you use permissions role resources custom

I have detected that this occurrence is related to the use of the "<config_path>" parameter that is required due to the use of the group type field

![captura de tela de 2017-11-16 13-14-44](https://user-images.githubusercontent.com/26491932/32898965-ca13c5b4-cad0-11e7-835a-ab5c991b5af1.png)
![captura de tela de 2017-11-16 13-14-56](https://user-images.githubusercontent.com/26491932/32898966-ca3de8f8-cad0-11e7-8a53-bcead3a0db3c.png)

**Comment by sabrinabandaree** [comment]
I have just found this occurrence recorded in

https://magento.com/tech-resources/bug-tracking/issue/index/id/1709/

**Comment by rikterbeek** [comment]
Hi @sabrinabandaree,

Looks like a core issue not sure we can fix this in our extension. We need have the config_path parameter for all our fields because we use a nest structure.

Regards,
Rik
Adyen
