### ISSUE TITLE
Notice: Undefined offset // pay_by_mail.phtml on line 50

### ISSUE THREAD

**Issue by seansan** [Adyen/adyen-magento#861]
**Magento version**: 1936
**Plugin version**: 2.9.5
**Description**

Only a notice, but maybe helps and can be prevented

2017-11-24T13:25:30+00:00 ERR (3): Notice: Undefined offset: 1  in public_html/app/design/adminhtml/default/default/template/adyen/info/pay_by_mail.phtml on line 50

**Comment by rikterbeek** [comment]
Hi @seansan,

For paybymail you do not know the bank selection because that is made on the HPP we will remove the code so this warning will be solved.

Regards,
Rik

**Comment by seansan** [comment]
@rikterbeek upgraded to latest version was still seeing this error. This fix is in develop? thx

**Comment by rikterbeek** [comment]
HI @seansan,

Indeed only on our develop branch. Will be in the next release.

Regards,
Rik
Adyen
