### ISSUE TITLE
SUPEE-10415, escaping additional columns in Adyen_Payment_Block_Adminhtml_Sales_Billing_Agreement_Grid

### ISSUE THREAD

**Issue by tr33m4n** [Adyen/adyen-magento#870]
**Magento version**: 1.14.2.2
**Plugin version**: 2.9.2/NA

**Description**
Since the release of SUPEE-10415, extra escaping has been added to `Mage_Sales_Block_Adminhtml_Billing_Agreement_Grid`:

```diff
$this->addColumn('customer_email', array(
            'header'            => Mage::helper('sales')->__('Customer Email'),
            'index'             => 'customer_email',
-           'type'              => 'text'
+           'type'              => 'text',
+           'escape'            => true
        ));
```

`Adyen_Payment_Block_Adminhtml_Sales_Billing_Agreement_Grid` however does not include any escaping in the fields it adds https://github.com/Adyen/adyen-magento/blob/develop/app/code/community/Adyen/Payment/Block/Adminhtml/Sales/Billing/Agreement/Grid.php#L68. Escaping for `customer_firstname` and `customer_lastname` have been present for a while and since `Adyen_Payment_Block_Adminhtml_Sales_Billing_Agreement_Grid` adds the field `name`, thought it might be relevant.

Just wondering whether this is intentional? Or is it indeed a security issue and should be amended?

**Comment by rikterbeek** [comment]
Hi @tr33m4n,

This is not intentional so let's add the esacping into our grid. Are you able to do a PR with this fix ?

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
Hi @tr33m4n,

We have added this into this PR: https://github.com/Adyen/adyen-magento/pull/960

Regards,
Rik
Adyen
