### ISSUE TITLE
adyen.encrypt_0_1_16.js causing forced reflows when using CreditCard input field.

### ISSUE THREAD

**Issue by NickdeK** [Adyen/adyen-magento#884]
**Magento version**: 1.9.2.4
**Plugin version**: 2.9.0
**Description**
The `adyen.encrypt_0_1_16.js` and `adyen.encrypt_0_1_18.js` is causing a lot of forced reflows in our checkout. This has apparently been a issue for a long time but just recently got some attention. 

The problem occurs when filling in a credit card number, after one or two digits the input field stops responding to any input for about 3 seconds. When recording the issue in the observer I see a function call in the `adyen.encrypt_0_1_16.js:204` that eventually calls the `getJsFonts` a lot. Chrome indicates this as the most likely cause for performance issues during the recording.

Tried to update to module to 2.9.6 and switching the encrypt js file to 1.18 without any luck. Also removed our theme rewrites on the `cc.phtml` with still the same problem.
![screen shot 2018-01-26 at 14 22 23](https://user-images.githubusercontent.com/6631170/35441593-678ca314-02a4-11e8-82a3-45667a5a37a2.png)

**Comment by rikterbeek** [comment]
Hi @NickdeK,

Could you raise this issue into our CSE repository see: https://github.com/Adyen/adyen-cse-web/blob/master/js/adyen.encrypt.js

Regards,
Rik
Adyen
