### ISSUE TITLE
Notice: Undefined index: productId

### ISSUE THREAD

**Issue by lykhouzov** [Adyen/adyen-magento#888]
https://github.com/Adyen/adyen-magento/blob/570e2ac3e1f7b32399c1b82a091a04a7fcd493b9/app/design/frontend/base/default/template/adyen/apple_pay.phtml#L4

When you available to show empty cart there is an issue with index

**Comment by rikterbeek** [comment]
Hi @lykhouzov,

Understood we can do the same as we do for finalPrice if empty just put it to zero. Are you able to do a PR for this fix ?

Regards,
Rik
Adyen

**Comment by lykhouzov** [comment]
hello @rikterbeek 
PR is created.

**Comment by rikterbeek** [comment]
Thanks!
