### ISSUE TITLE
problem with configuring module v2.10.0 on magento 1.9.3

### ISSUE THREAD

**Issue by hristopeev** [Adyen/adyen-magento#893]
**Magento version**: 1.9.3
**Plugin version**: 2.10.0
**Description**

Hello,

I have a problem with configuring your module. After I installed it I am trying to setup server notificaitons, but seems that the endpoint ```/adyen/process/json``` is not accessible.

When I try to test the configuration, the following error occurs:

```
The required string "[accepted]" is not in all the results
```

<img width="545" alt="screenshot 2018-02-16 12 09 49" src="https://user-images.githubusercontent.com/1288622/36302837-9ed47756-1312-11e8-9650-be97d837e11b.png">

I tried to add the following rules in ```.htaccess``` file but it did not help.

```
RewriteEngine on:
RewriteCond %{HTTP:Authorization} (.+)
RewriteRule .* - [E=REMOTE_USER:%{HTTP:Authorization},L]
```

Can you, please, help with troubleshooting the problem?
Do I need to do something more besides the installing the module which will enable the endpoint.

If any additional information related to the environment is needed I am ready to provide it.

**Comment by rikterbeek** [comment]
Hi @hristopeev,

Probably your endpoint in not correctly configured. Maybe you need to add index.php after the bas url if this does not work please send email to magento@adyen.com and provide merchantAccount and Url then we are able to help out.

Regards,
Rik
Adyen
