### ISSUE TITLE
Billing agreement - credit card expiration date is not updated

### ISSUE THREAD

**Issue by atty31** [Adyen/adyen-magento#896]
**Magento version**: 1.14.3.8
**Plugin version**: "adyen/payment": "^2.9"
**Description**
Billing agreement expiration date from Magento is not updated. 
![screenshot](https://user-images.githubusercontent.com/3530315/36963606-3c69d198-2054-11e8-8205-544bd926c9a6.png)

When I change the expiration date when I created an order (see img attached),  the values selected from the 2 dropdowns  are not used to update the billing agreement credit card expiration date from Magento.
`sales_flat_agreement` table -> `agreement_data` table

The 2 dropdowns can be found in this file: app/design/adminhtml/default/default/template/adyen/form/oneclick.phtml and they doesn't have the `name` html attribute because of this function `isCseEnabled()`, so I cannot get their value in the post request to update the BA in an observer, for instance.

Could you advice how to fix that issue? 

Thank you in advance !

**Comment by rikterbeek** [comment]
Hi @atty31,

The expiration date if this is changed it will be into the CSE encryption when the payment is successful processed it will update later in our database the new expiration date and will send this to magento. This will update the  agreement_data table. Could you provide me the first and second payment pspreference so I can check if we did receive the new pspreference. Best to provide this info to our support team at magento@adyen.com.

Regards,
Rik
Adyen
