### ISSUE TITLE
PSP reference link leads to Test Customer Area instead of live one with Production Mode.

### ISSUE THREAD

**Issue by lykhouzov** [Adyen/adyen-magento#904]
**Magento version**: 1.14.3.8
**Plugin version**: 2.10.0
**Description**
PSP reference link leads to **test customer area** instead of **live** one with Production Mode.
this happens for all payment method provided by Adyen, except CC and ApplePay.

The issue happens because of missing proper store ID in a template for payment block info.
this is app/design/adminhtml/default/default/template/adyen/info/hpp.phtml
```php
        <?php if ($this->getMethod()->getConfigDataDemoMode()): ?>
            <?php echo Mage::helper('adyen')->__('Adyen PSP Reference: <a href="https://ca-test.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=%s&txType=Payment" target="__blank">%s</a>', $this->htmlEscape($_info->getAdyenPspReference()), $this->htmlEscape($_info->getAdyenPspReference())) ?>
            <br/>
        <?php else : ?>
            <?php echo Mage::helper('adyen')->__('Adyen PSP Reference: <a href="https://ca-live.adyen.com/ca/ca/accounts/showTx.shtml?pspReference=%s&txType=Payment" target="__blank">%s</a>', $this->htmlEscape($_info->getAdyenPspReference()), $this->htmlEscape($_info->getAdyenPspReference())) ?>
            <br/>
```
And as you can see in order to detect whether it test mode or production one id does not consider order's store id.

**Comment by rikterbeek** [comment]
Hi @lykhouzov,

I see the problem indeed. Can you check if the below fix solves your issue ?

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment]
@lykhouzov,

This fix is included in the latest release.

Regards,
Rik
Adyen
