### ISSUE TITLE
How to Send Order Confirmation Email After Successful Payment in Magento 2--paytm

### ISSUE THREAD

**Issue by chalapathipakkela** [Adyen/adyen-magento#905]
**Magento version**:2.1.7
**Plugin version**: 1
**Description**

**Comment by chalapathipakkela** [comment]
Customer chooses to pay by Paytm -> Is redirected to Paytm gateway -> Magento IMMEDIATELY sends out an Order Confirmation Email to the customer, before he even completes the payment.How to Send Order Confirmation Email After Successful Payment in Magento 2--paytm

**Comment by rikterbeek** [comment]
Hi @chalapathipakkela,

This extension is for Magento1. I think you are referring to a other gateway then Adyen so I would advise you to contact them.

Regards,
Rik
Adyen
