### ISSUE TITLE
js/adyen/payment/cc.js First line

### ISSUE THREAD

**Issue by neonbcn** [Adyen/adyen-magento#909]
**Magento version**: 1.9.3.8
**Plugin version**: 2.1.0
**Description**
The first line of js/adyen/payment/cc.js file has a invalid Javascript comment sintax:

`<!-- Original:  Simon Tneoh (tneohcb@pc.jaring.my) -->`

That causes a error when Magento merges Javascript files and I have to exclude it from merge.

**Comment by rikterbeek** [comment]
Hi @neonbcn,

Thanks for addressing this issue. We will solve it by removing this line.

Regards,
Rik
Adyen
