### ISSUE TITLE
Where is "How did you hear about us?"

### ISSUE THREAD

**Issue by reecreateeduardo** [Adyen/adyen-magento#914]
**Magento version**: 1.9.3
**Plugin version**: 2.10
**Description**

I can't find "How did you hear about us?"

I am on system -> configuration ->payment methods -> Adyen but nothing

Any help? Thanks

**Comment by rikterbeek** [comment]
Hi @reecreateeduardo,

I am not sure what you mean I don't think this comes from our extension. Can you provide a screenshot to clarify what you mean ?

Regards,
Rik
Adyen

**Comment by reecreateeduardo** [comment]
Hi,

I was under the impression you plugin had a part on the checkout that the customer would have a dropbox or a text field followed with the question "how did you hear about us?"

**Comment by rikterbeek** [comment]
Hi @reecreateeduardo,

No we don't. We only focus on payment methods integration and try to be on the back so you don't notice us. Closing the issue.

Regards,
Rik
Adyen
