### ISSUE TITLE
refund order in different currency basegrandtotal is wrong (should be price in current store currency)

### ISSUE THREAD

**Issue by lortizcompegps** [Adyen/adyen-magento#915]
**Magento version**: 1.8.0
**Plugin version**: 2.8.0
**Description**

When an order in a different currency is done, and after we do a refund from adyen platform.
The process to calculate basegrandtotal is not correct, and it puts same as grandtotal.

It should be same price as default currency store, that in my case is in EUR.

We have an example in AU$, and when we look for the creditmemo data we confirm that 
basegrandtotal and grandtotal are the same.

I think this process is done here:
app\code\community\Adyen\Payment\Model\ProcessNotification.php

protected function _refundOrder($order)

We can see that here:
line 767
`       
if ($order->canCreditmemo()) {
            $service = Mage::getModel('sales/service_order', $order);
            $creditmemo = $service->prepareCreditmemo();
            $creditmemo->getOrder()->setIsInProcess(true);
            //set refund data on the order
            $creditmemo->setGrandTotal($amount);
            $creditmemo->setBaseGrandTotal($amount);
            $creditmemo->save();
`

I propose this change, in order to detect if total amount to refund, if is it same as the order total amount, we can put same as the order, something like this

`           
          $creditmemo->setBaseGrandTotal($amount);

            $testAmount = number_format("" . $amount, 2, '.', '');
            $testOrderAmount = number_format("" . $creditmemo->getOrder()->getGrandTotal(), 2, '.', '');
            $testOrderBaseAmount = number_format("" . $creditmemo->getOrder()->getBaseGrandTotal(), 2, '.', '');

            if ($testAmount == $testOrderAmount &&
                $testOrderAmount != $testOrderBaseAmount) {
                $creditmemo->setBaseGrandTotal($testOrderBaseAmount);
            }

            $creditmemo->save();
`

This change will only save setBaseGrandTotal, in this case.

Thank you

**Comment by rikterbeek** [comment]
Hi @lortizcompegps,

I would highly advise you to do refunds from inside Magento is that possible for you ?
As well I see you are on a old version of the extension are you able to upgrade this to latest version ?

Regards,
Rik
Adyen

**Comment by lortizcompegps** [comment]
In order to avoid more steps in a refund proces, we let automatic refund option active.

This happen to us 1 time in 3 years, so i think we will keep this as it is. This issue only made something wrong when we export data to our accounting ERP, but we detected the difference and fix the creditmemo.

We suggest if it is possible to do this improvement, i don't know what do you think if someone else will have this kind of issue... Maybe you can take into account this fix.

If not... we can close this issue

Thank you

**Comment by rikterbeek** [comment]
Hi @lortizcompegps,

As this is an issue that does not occur often and I see problems in changing this logic for other merchants let's keep it as it is. You are always free to open a PR with the changes you need so we can do more investigation on our end if it cover all cases.

Regards,
Rik
Adyen
