### ISSUE TITLE
Consider Moving Adyen_Fee To It's Own Repository

### ISSUE THREAD

**Issue by drobinson** [Adyen/adyen-magento#925]
**Magento version**: n/a
**Plugin version**: n/a
**Description**
I would like to disable/remove the Adyen_Fee module as it is not needed for us and has some conflicts with out custom code.  I would prefer to remove it via composer.json instead of forking this repository, but it doesn't seem like that's possible at the moment.

Would you consider moving it to its own repository and "suggesting" it via composer?

**Comment by rikterbeek** [comment]
HI @drobinson,

At the moment we do not think of moving it over to an other repository. We will think about if it should be on by default as many clients don't use it and it is not PSD2 compliant for european customers.
For now I would say just disable the module here: https://github.com/Adyen/adyen-magento/blob/develop/app/etc/modules/Adyen_Payment.xml#L36

Regards,
Rik
Adyen

**Comment by drobinson** [comment]
Got it.  That's what we ended up doing - however, if your users want to pull in the repository via Composer, then they will have to fork this repo to make that change (vs excluding in their composer.json).

The problem with this module is that it has some rewrites that are very likely to conflict with custom code (in the totals collectors, for instance).
