### ISSUE TITLE
Clearing checkout session after redirect from 3d secure page on cvv or cvc failure

### ISSUE THREAD

**Issue by charleskj** [Adyen/adyen-magento#929]
**Magento version**: EE 1.14.3.8 

**Plugin version**: 2.10.0  

**Description**

- When redirect from 3d secure page on cvc or cvv  failure, it is not showing any error message as well as clearing checkout session.
- This is working fine for non 3d secure cards

**Comment by charleskj** [comment]
Any update on this ?

**Comment by charleskj** [comment]
@rikterbeek 

Magento and extension version are mentioned in my first comment in this issue.
Your extension provides a option to redirect either to cart or checkout. Redirect to cart works fine and showing error message properly.
Problem is with redirect option to checkout page, when we turn this option on, error message will not display in checkout.

As I mentioned in the first comment 
- When redirect from 3d secure page on cvc or cvv failure, it is not showing any error message as well as clearing checkout session.
- This is working fine for non 3d secure cards
![configuration system magento admin 1](https://user-images.githubusercontent.com/3807333/44712056-8cad8600-aacd-11e8-8238-7c51bd871d43.png)

**Comment by rikterbeek** [comment]
Hi @charleskj,

Indeed the checkout is not working as this is as far as I know not showing any error messages. Just to recap you do get error messages when it does not contain a 3D secure payment and running back to the checkout ? Did you contact Magento about this as well, as we our not in control on what error messages will be displayed on the checkout page.

Regards,
Rik
Adyen

**Comment by charleskj** [comment]
@rikterbeek  yes error message is displaying if there is no 3d secure for card payment.
So it seems like checkout session is either cleared or not matching when customer  come back from 3d secure page.

**Comment by ScottPowell14** [comment]
Hi @charleskj, the error message for non 3D secure cards is through exception printing on the checkout page. For the redirect back to the checkout page, this behavior is disabled by default by magento. The session data is not actually cleared as you can navigate to the cart to see the error messages and the shopper's items restored. You may need to create a custom error messages template for the checkout page and load the session's error messages accordingly. 

Thanks for bringing the issue to our attention.

Regards,
Scott
Adyen
