### ISSUE TITLE
Admin order no longer working

### ISSUE THREAD

**Issue by hughconway** [Adyen/adyen-magento#983]
**Magento version**: 1.9.0.1
**Plugin version**: 2.13.0
**Description**

I have just upgraded to 2.13.0 from 2.12.2 but now cannot place an order via the admin Create New Order screen when using Adyen as the payment method. The Submit Order can be clicked but nothing happens. I have tested other admin payment methods and all work fine apart from Adyen.

The card details section loads correctly (for both saved and new cards) and appears to function with the card type changing based on the card number and the ticks appearing when valid data has been entered.

The front end still works fine with Adyen so there seems to be a conflict in the Admin area alone preventing the order submitting when the Adyen module is selected as the payment method.

I cannot immediately see any JS conflicts but assume that this is what it must be.

Has anyone else come across this?

Thanks,

Hugh

**Comment by hughconway** [comment]
Have emailed Adyen support regarding this issue.

**Comment by atty31** [comment]
@hughconway  did you fix this ? I am facing the same issue

**Comment by hughconway** [comment]
No. I downgraded back to the previous version of the plugin.On 16 Apr 2019 15:09, Attila Naghi <notifications@github.com> wrote:@hughconway  did you fix this ? I am facing the same issue

**Comment by atty31** [comment]
@hughconway , 
Can you give another try ? by removing a </div> from line 77: https://github.com/Adyen/adyen-magento/blob/develop/app/design/adminhtml/default/default/template/adyen/form/cc.phtml#L77   works for me  .
I think that closed div is messing up the js code.

**Comment by hughconway** [comment]
Thanks, that seems to have been the problem as it's working now :) 

On 2019-04-17 12:19, Attila Naghi wrote:

> @hughconway [1] ,
> Can you give another try ? by removing a from line 77: https://github.com/Adyen/adyen-magento/blob/develop/app/design/adminhtml/default/default/template/adyen/form/cc.phtml#L77 works for me .
> I think that closed div is messing up the js code. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/hughconway
[2]
https://github.com/Adyen/adyen-magento/issues/983#issuecomment-484042252
[3]

**Comment by atty31** [comment]
@Aleffio Can you do a hotfix for this ? Thnx!

**Comment by hughconway** [comment]
How?

---
Hugh Conway 

Sconch
01376 743123
www.sconch.com 

On 2019-04-17 13:54, Attila Naghi wrote:

> @Aleffio [1] Can you do a hotfix for this ? Thnx! 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/Aleffio
[2]
https://github.com/Adyen/adyen-magento/issues/983#issuecomment-484071656
[3]

**Comment by Aleffio** [comment]
Hi @atty31 ,
thank you for the fix, we are going to merge it asap.

Kind Regards,
Alessio
Adyen
