### ISSUE TITLE
Adyen cookies needs not to be set as module is disabled

### ISSUE THREAD

**Issue by martijnrmediact** [Adyen/adyen-magento#984]
**Magento version**: 1.14.4
**Plugin version**: latest
**Description**

Adyen sets a cookie when placing an order, this cookie is named JSESSIONID and is set by the domain live.adyen.com. It's probably a functional cookie and is necessary when Adyen is used as a PSP. The cookie is loaded when the module is enabled but also when the module is disabled from the configuration. The cookie should only be loaded when Adyen is enabled for a website/store/view.

**Comment by martijnrmediact** [comment]
@cyattilakiss any update on this from you side?

**Comment by Aleffio** [comment]
Hi @martijnrmediact ,
The module does not handle the cookie, if you want to know more about the cookie and its purpose, please contact support@adyen.com

Kind Regards,
Alessio
Adyen
